// Code generated by ent, DO NOT EDIT.

package featureflag

import (
	"backend-gin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldDeletedAt, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldEnabled, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldDescription, v))
}

// RolloutPercentage applies equality check predicate on the "rollout_percentage" field. It's identical to RolloutPercentageEQ.
func RolloutPercentage(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldRolloutPercentage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotNull(FieldDeletedAt))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldContainsFold(FieldKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldEnabled, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldContainsFold(FieldDescription, v))
}

// RolloutPercentageEQ applies the EQ predicate on the "rollout_percentage" field.
func RolloutPercentageEQ(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldEQ(FieldRolloutPercentage, v))
}

// RolloutPercentageNEQ applies the NEQ predicate on the "rollout_percentage" field.
func RolloutPercentageNEQ(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNEQ(FieldRolloutPercentage, v))
}

// RolloutPercentageIn applies the In predicate on the "rollout_percentage" field.
func RolloutPercentageIn(vs ...int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldIn(FieldRolloutPercentage, vs...))
}

// RolloutPercentageNotIn applies the NotIn predicate on the "rollout_percentage" field.
func RolloutPercentageNotIn(vs ...int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldNotIn(FieldRolloutPercentage, vs...))
}

// RolloutPercentageGT applies the GT predicate on the "rollout_percentage" field.
func RolloutPercentageGT(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGT(FieldRolloutPercentage, v))
}

// RolloutPercentageGTE applies the GTE predicate on the "rollout_percentage" field.
func RolloutPercentageGTE(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldGTE(FieldRolloutPercentage, v))
}

// RolloutPercentageLT applies the LT predicate on the "rollout_percentage" field.
func RolloutPercentageLT(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLT(FieldRolloutPercentage, v))
}

// RolloutPercentageLTE applies the LTE predicate on the "rollout_percentage" field.
func RolloutPercentageLTE(v int) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.FieldLTE(FieldRolloutPercentage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FeatureFlag) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FeatureFlag) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FeatureFlag) predicate.FeatureFlag {
	return predicate.FeatureFlag(sql.NotPredicates(p))
}
