// Code generated by ent, DO NOT EDIT.

package validationcaselog

import (
	"backend-gin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldDeletedAt, v))
}

// ValidationCaseID applies equality check predicate on the "validation_case_id" field. It's identical to ValidationCaseIDEQ.
func ValidationCaseID(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldValidationCaseID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldActorUserID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldEventType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotNull(FieldDeletedAt))
}

// ValidationCaseIDEQ applies the EQ predicate on the "validation_case_id" field.
func ValidationCaseIDEQ(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDNEQ applies the NEQ predicate on the "validation_case_id" field.
func ValidationCaseIDNEQ(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDIn applies the In predicate on the "validation_case_id" field.
func ValidationCaseIDIn(vs ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldValidationCaseID, vs...))
}

// ValidationCaseIDNotIn applies the NotIn predicate on the "validation_case_id" field.
func ValidationCaseIDNotIn(vs ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldValidationCaseID, vs...))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotNull(FieldActorUserID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldContainsFold(FieldEventType, v))
}

// DetailJSONIsNil applies the IsNil predicate on the "detail_json" field.
func DetailJSONIsNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldIsNull(FieldDetailJSON))
}

// DetailJSONNotNil applies the NotNil predicate on the "detail_json" field.
func DetailJSONNotNil() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.FieldNotNull(FieldDetailJSON))
}

// HasValidationCase applies the HasEdge predicate on the "validation_case" edge.
func HasValidationCase() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ValidationCaseTable, ValidationCaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasValidationCaseWith applies the HasEdge predicate on the "validation_case" edge with a given conditions (other predicates).
func HasValidationCaseWith(preds ...predicate.ValidationCase) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(func(s *sql.Selector) {
		step := newValidationCaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActorUser applies the HasEdge predicate on the "actor_user" edge.
func HasActorUser() predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActorUserTable, ActorUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorUserWith applies the HasEdge predicate on the "actor_user" edge with a given conditions (other predicates).
func HasActorUserWith(preds ...predicate.User) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(func(s *sql.Selector) {
		step := newActorUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ValidationCaseLog) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ValidationCaseLog) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ValidationCaseLog) predicate.ValidationCaseLog {
	return predicate.ValidationCaseLog(sql.NotPredicates(p))
}
