// Code generated by ent, DO NOT EDIT.

package validationcase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the validationcase type in the database.
	Label = "validation_case"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldContentJSON holds the string denoting the content_json field in the database.
	FieldContentJSON = "content_json"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldBountyAmount holds the string denoting the bounty_amount field in the database.
	FieldBountyAmount = "bounty_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEscrowTransferID holds the string denoting the escrow_transfer_id field in the database.
	FieldEscrowTransferID = "escrow_transfer_id"
	// FieldDisputeID holds the string denoting the dispute_id field in the database.
	FieldDisputeID = "dispute_id"
	// FieldAcceptedFinalOfferID holds the string denoting the accepted_final_offer_id field in the database.
	FieldAcceptedFinalOfferID = "accepted_final_offer_id"
	// FieldArtifactDocumentID holds the string denoting the artifact_document_id field in the database.
	FieldArtifactDocumentID = "artifact_document_id"
	// FieldCertifiedArtifactDocumentID holds the string denoting the certified_artifact_document_id field in the database.
	FieldCertifiedArtifactDocumentID = "certified_artifact_document_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeCaseLogs holds the string denoting the case_logs edge name in mutations.
	EdgeCaseLogs = "case_logs"
	// EdgeConsultationRequests holds the string denoting the consultation_requests edge name in mutations.
	EdgeConsultationRequests = "consultation_requests"
	// EdgeFinalOffers holds the string denoting the final_offers edge name in mutations.
	EdgeFinalOffers = "final_offers"
	// EdgeArtifactSubmissions holds the string denoting the artifact_submissions edge name in mutations.
	EdgeArtifactSubmissions = "artifact_submissions"
	// EdgeEndorsements holds the string denoting the endorsements edge name in mutations.
	EdgeEndorsements = "endorsements"
	// Table holds the table name of the validationcase in the database.
	Table = "validation_cases"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "validation_cases"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "validation_cases"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_id"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "tag_validation_cases"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// CaseLogsTable is the table that holds the case_logs relation/edge.
	CaseLogsTable = "validation_case_logs"
	// CaseLogsInverseTable is the table name for the ValidationCaseLog entity.
	// It exists in this package in order to avoid circular dependency with the "validationcaselog" package.
	CaseLogsInverseTable = "validation_case_logs"
	// CaseLogsColumn is the table column denoting the case_logs relation/edge.
	CaseLogsColumn = "validation_case_id"
	// ConsultationRequestsTable is the table that holds the consultation_requests relation/edge.
	ConsultationRequestsTable = "consultation_requests"
	// ConsultationRequestsInverseTable is the table name for the ConsultationRequest entity.
	// It exists in this package in order to avoid circular dependency with the "consultationrequest" package.
	ConsultationRequestsInverseTable = "consultation_requests"
	// ConsultationRequestsColumn is the table column denoting the consultation_requests relation/edge.
	ConsultationRequestsColumn = "validation_case_id"
	// FinalOffersTable is the table that holds the final_offers relation/edge.
	FinalOffersTable = "final_offers"
	// FinalOffersInverseTable is the table name for the FinalOffer entity.
	// It exists in this package in order to avoid circular dependency with the "finaloffer" package.
	FinalOffersInverseTable = "final_offers"
	// FinalOffersColumn is the table column denoting the final_offers relation/edge.
	FinalOffersColumn = "validation_case_id"
	// ArtifactSubmissionsTable is the table that holds the artifact_submissions relation/edge.
	ArtifactSubmissionsTable = "artifact_submissions"
	// ArtifactSubmissionsInverseTable is the table name for the ArtifactSubmission entity.
	// It exists in this package in order to avoid circular dependency with the "artifactsubmission" package.
	ArtifactSubmissionsInverseTable = "artifact_submissions"
	// ArtifactSubmissionsColumn is the table column denoting the artifact_submissions relation/edge.
	ArtifactSubmissionsColumn = "validation_case_id"
	// EndorsementsTable is the table that holds the endorsements relation/edge.
	EndorsementsTable = "endorsements"
	// EndorsementsInverseTable is the table name for the Endorsement entity.
	// It exists in this package in order to avoid circular dependency with the "endorsement" package.
	EndorsementsInverseTable = "endorsements"
	// EndorsementsColumn is the table column denoting the endorsements relation/edge.
	EndorsementsColumn = "validation_case_id"
)

// Columns holds all SQL columns for validationcase fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCategoryID,
	FieldUserID,
	FieldTitle,
	FieldSummary,
	FieldContentType,
	FieldContentJSON,
	FieldMeta,
	FieldBountyAmount,
	FieldStatus,
	FieldEscrowTransferID,
	FieldDisputeID,
	FieldAcceptedFinalOfferID,
	FieldArtifactDocumentID,
	FieldCertifiedArtifactDocumentID,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"tag_id", "validation_case_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	CategoryIDValidator func(int) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultContentType holds the default value on creation for the "content_type" field.
	DefaultContentType string
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// DefaultBountyAmount holds the default value on creation for the "bounty_amount" field.
	DefaultBountyAmount int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// AcceptedFinalOfferIDValidator is a validator for the "accepted_final_offer_id" field. It is called by the builders before save.
	AcceptedFinalOfferIDValidator func(int) error
)

// OrderOption defines the ordering options for the ValidationCase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByBountyAmount orders the results by the bounty_amount field.
func ByBountyAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBountyAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEscrowTransferID orders the results by the escrow_transfer_id field.
func ByEscrowTransferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEscrowTransferID, opts...).ToFunc()
}

// ByDisputeID orders the results by the dispute_id field.
func ByDisputeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisputeID, opts...).ToFunc()
}

// ByAcceptedFinalOfferID orders the results by the accepted_final_offer_id field.
func ByAcceptedFinalOfferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedFinalOfferID, opts...).ToFunc()
}

// ByArtifactDocumentID orders the results by the artifact_document_id field.
func ByArtifactDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactDocumentID, opts...).ToFunc()
}

// ByCertifiedArtifactDocumentID orders the results by the certified_artifact_document_id field.
func ByCertifiedArtifactDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertifiedArtifactDocumentID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCaseLogsCount orders the results by case_logs count.
func ByCaseLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCaseLogsStep(), opts...)
	}
}

// ByCaseLogs orders the results by case_logs terms.
func ByCaseLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCaseLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByConsultationRequestsCount orders the results by consultation_requests count.
func ByConsultationRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConsultationRequestsStep(), opts...)
	}
}

// ByConsultationRequests orders the results by consultation_requests terms.
func ByConsultationRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsultationRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFinalOffersCount orders the results by final_offers count.
func ByFinalOffersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFinalOffersStep(), opts...)
	}
}

// ByFinalOffers orders the results by final_offers terms.
func ByFinalOffers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFinalOffersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByArtifactSubmissionsCount orders the results by artifact_submissions count.
func ByArtifactSubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArtifactSubmissionsStep(), opts...)
	}
}

// ByArtifactSubmissions orders the results by artifact_submissions terms.
func ByArtifactSubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArtifactSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEndorsementsCount orders the results by endorsements count.
func ByEndorsementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEndorsementsStep(), opts...)
	}
}

// ByEndorsements orders the results by endorsements terms.
func ByEndorsements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEndorsementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TagsTable, TagsPrimaryKey...),
	)
}
func newCaseLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CaseLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CaseLogsTable, CaseLogsColumn),
	)
}
func newConsultationRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsultationRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ConsultationRequestsTable, ConsultationRequestsColumn),
	)
}
func newFinalOffersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FinalOffersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FinalOffersTable, FinalOffersColumn),
	)
}
func newArtifactSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArtifactSubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ArtifactSubmissionsTable, ArtifactSubmissionsColumn),
	)
}
func newEndorsementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EndorsementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EndorsementsTable, EndorsementsColumn),
	)
}
