// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/artifactsubmission"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtifactSubmissionCreate is the builder for creating a ArtifactSubmission entity.
type ArtifactSubmissionCreate struct {
	config
	mutation *ArtifactSubmissionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArtifactSubmissionCreate) SetCreatedAt(v time.Time) *ArtifactSubmissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArtifactSubmissionCreate) SetNillableCreatedAt(v *time.Time) *ArtifactSubmissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArtifactSubmissionCreate) SetUpdatedAt(v time.Time) *ArtifactSubmissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArtifactSubmissionCreate) SetNillableUpdatedAt(v *time.Time) *ArtifactSubmissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ArtifactSubmissionCreate) SetDeletedAt(v time.Time) *ArtifactSubmissionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ArtifactSubmissionCreate) SetNillableDeletedAt(v *time.Time) *ArtifactSubmissionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_c *ArtifactSubmissionCreate) SetValidationCaseID(v int) *ArtifactSubmissionCreate {
	_c.mutation.SetValidationCaseID(v)
	return _c
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_c *ArtifactSubmissionCreate) SetValidatorUserID(v int) *ArtifactSubmissionCreate {
	_c.mutation.SetValidatorUserID(v)
	return _c
}

// SetDocumentID sets the "document_id" field.
func (_c *ArtifactSubmissionCreate) SetDocumentID(v string) *ArtifactSubmissionCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_c *ArtifactSubmissionCreate) SetValidationCase(v *ValidationCase) *ArtifactSubmissionCreate {
	return _c.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_c *ArtifactSubmissionCreate) SetValidatorUser(v *User) *ArtifactSubmissionCreate {
	return _c.SetValidatorUserID(v.ID)
}

// Mutation returns the ArtifactSubmissionMutation object of the builder.
func (_c *ArtifactSubmissionCreate) Mutation() *ArtifactSubmissionMutation {
	return _c.mutation
}

// Save creates the ArtifactSubmission in the database.
func (_c *ArtifactSubmissionCreate) Save(ctx context.Context) (*ArtifactSubmission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArtifactSubmissionCreate) SaveX(ctx context.Context) *ArtifactSubmission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactSubmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactSubmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArtifactSubmissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := artifactsubmission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := artifactsubmission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArtifactSubmissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArtifactSubmission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArtifactSubmission.updated_at"`)}
	}
	if _, ok := _c.mutation.ValidationCaseID(); !ok {
		return &ValidationError{Name: "validation_case_id", err: errors.New(`ent: missing required field "ArtifactSubmission.validation_case_id"`)}
	}
	if v, ok := _c.mutation.ValidationCaseID(); ok {
		if err := artifactsubmission.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactSubmission.validation_case_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidatorUserID(); !ok {
		return &ValidationError{Name: "validator_user_id", err: errors.New(`ent: missing required field "ArtifactSubmission.validator_user_id"`)}
	}
	if v, ok := _c.mutation.ValidatorUserID(); ok {
		if err := artifactsubmission.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactSubmission.validator_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "ArtifactSubmission.document_id"`)}
	}
	if v, ok := _c.mutation.DocumentID(); ok {
		if err := artifactsubmission.DocumentIDValidator(v); err != nil {
			return &ValidationError{Name: "document_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactSubmission.document_id": %w`, err)}
		}
	}
	if len(_c.mutation.ValidationCaseIDs()) == 0 {
		return &ValidationError{Name: "validation_case", err: errors.New(`ent: missing required edge "ArtifactSubmission.validation_case"`)}
	}
	if len(_c.mutation.ValidatorUserIDs()) == 0 {
		return &ValidationError{Name: "validator_user", err: errors.New(`ent: missing required edge "ArtifactSubmission.validator_user"`)}
	}
	return nil
}

func (_c *ArtifactSubmissionCreate) sqlSave(ctx context.Context) (*ArtifactSubmission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArtifactSubmissionCreate) createSpec() (*ArtifactSubmission, *sqlgraph.CreateSpec) {
	var (
		_node = &ArtifactSubmission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(artifactsubmission.Table, sqlgraph.NewFieldSpec(artifactsubmission.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(artifactsubmission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactsubmission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(artifactsubmission.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DocumentID(); ok {
		_spec.SetField(artifactsubmission.FieldDocumentID, field.TypeString, value)
		_node.DocumentID = value
	}
	if nodes := _c.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifactsubmission.ValidationCaseTable,
			Columns: []string{artifactsubmission.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidationCaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifactsubmission.ValidatorUserTable,
			Columns: []string{artifactsubmission.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidatorUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ArtifactSubmissionCreateBulk is the builder for creating many ArtifactSubmission entities in bulk.
type ArtifactSubmissionCreateBulk struct {
	config
	err      error
	builders []*ArtifactSubmissionCreate
}

// Save creates the ArtifactSubmission entities in the database.
func (_c *ArtifactSubmissionCreateBulk) Save(ctx context.Context) ([]*ArtifactSubmission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ArtifactSubmission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtifactSubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArtifactSubmissionCreateBulk) SaveX(ctx context.Context) []*ArtifactSubmission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactSubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactSubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
