// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/chaincursor"
	"backend-gin/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChainCursorDelete is the builder for deleting a ChainCursor entity.
type ChainCursorDelete struct {
	config
	hooks    []Hook
	mutation *ChainCursorMutation
}

// Where appends a list predicates to the ChainCursorDelete builder.
func (_d *ChainCursorDelete) Where(ps ...predicate.ChainCursor) *ChainCursorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChainCursorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChainCursorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChainCursorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chaincursor.Table, sqlgraph.NewFieldSpec(chaincursor.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChainCursorDeleteOne is the builder for deleting a single ChainCursor entity.
type ChainCursorDeleteOne struct {
	_d *ChainCursorDelete
}

// Where appends a list predicates to the ChainCursorDelete builder.
func (_d *ChainCursorDeleteOne) Where(ps ...predicate.ChainCursor) *ChainCursorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChainCursorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chaincursor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChainCursorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
