// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/chaincursor"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChainCursorCreate is the builder for creating a ChainCursor entity.
type ChainCursorCreate struct {
	config
	mutation *ChainCursorMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ChainCursorCreate) SetName(v string) *ChainCursorCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *ChainCursorCreate) SetChainID(v uint64) *ChainCursorCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetLastProcessed sets the "last_processed" field.
func (_c *ChainCursorCreate) SetLastProcessed(v uint64) *ChainCursorCreate {
	_c.mutation.SetLastProcessed(v)
	return _c
}

// SetNillableLastProcessed sets the "last_processed" field if the given value is not nil.
func (_c *ChainCursorCreate) SetNillableLastProcessed(v *uint64) *ChainCursorCreate {
	if v != nil {
		_c.SetLastProcessed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChainCursorCreate) SetCreatedAt(v time.Time) *ChainCursorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChainCursorCreate) SetNillableCreatedAt(v *time.Time) *ChainCursorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChainCursorCreate) SetUpdatedAt(v time.Time) *ChainCursorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChainCursorCreate) SetNillableUpdatedAt(v *time.Time) *ChainCursorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ChainCursorMutation object of the builder.
func (_c *ChainCursorCreate) Mutation() *ChainCursorMutation {
	return _c.mutation
}

// Save creates the ChainCursor in the database.
func (_c *ChainCursorCreate) Save(ctx context.Context) (*ChainCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChainCursorCreate) SaveX(ctx context.Context) *ChainCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChainCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChainCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChainCursorCreate) defaults() {
	if _, ok := _c.mutation.LastProcessed(); !ok {
		v := chaincursor.DefaultLastProcessed
		_c.mutation.SetLastProcessed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chaincursor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chaincursor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChainCursorCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChainCursor.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := chaincursor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChainCursor.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "ChainCursor.chain_id"`)}
	}
	if _, ok := _c.mutation.LastProcessed(); !ok {
		return &ValidationError{Name: "last_processed", err: errors.New(`ent: missing required field "ChainCursor.last_processed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChainCursor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChainCursor.updated_at"`)}
	}
	return nil
}

func (_c *ChainCursorCreate) sqlSave(ctx context.Context) (*ChainCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChainCursorCreate) createSpec() (*ChainCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &ChainCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chaincursor.Table, sqlgraph.NewFieldSpec(chaincursor.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chaincursor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(chaincursor.FieldChainID, field.TypeUint64, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.LastProcessed(); ok {
		_spec.SetField(chaincursor.FieldLastProcessed, field.TypeUint64, value)
		_node.LastProcessed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chaincursor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chaincursor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ChainCursorCreateBulk is the builder for creating many ChainCursor entities in bulk.
type ChainCursorCreateBulk struct {
	config
	err      error
	builders []*ChainCursorCreate
}

// Save creates the ChainCursor entities in the database.
func (_c *ChainCursorCreateBulk) Save(ctx context.Context) ([]*ChainCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChainCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChainCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChainCursorCreateBulk) SaveX(ctx context.Context) []*ChainCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChainCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChainCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
