// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/consultationrequest"
	"backend-gin/ent/predicate"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConsultationRequestUpdate is the builder for updating ConsultationRequest entities.
type ConsultationRequestUpdate struct {
	config
	hooks    []Hook
	mutation *ConsultationRequestMutation
}

// Where appends a list predicates to the ConsultationRequestUpdate builder.
func (_u *ConsultationRequestUpdate) Where(ps ...predicate.ConsultationRequest) *ConsultationRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConsultationRequestUpdate) SetUpdatedAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ConsultationRequestUpdate) SetDeletedAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableDeletedAt(v *time.Time) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ConsultationRequestUpdate) ClearDeletedAt() *ConsultationRequestUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_u *ConsultationRequestUpdate) SetValidationCaseID(v int) *ConsultationRequestUpdate {
	_u.mutation.SetValidationCaseID(v)
	return _u
}

// SetNillableValidationCaseID sets the "validation_case_id" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableValidationCaseID(v *int) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetValidationCaseID(*v)
	}
	return _u
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_u *ConsultationRequestUpdate) SetValidatorUserID(v int) *ConsultationRequestUpdate {
	_u.mutation.SetValidatorUserID(v)
	return _u
}

// SetNillableValidatorUserID sets the "validator_user_id" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableValidatorUserID(v *int) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetValidatorUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConsultationRequestUpdate) SetStatus(v string) *ConsultationRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableStatus(v *string) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *ConsultationRequestUpdate) SetApprovedAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableApprovedAt(v *time.Time) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *ConsultationRequestUpdate) ClearApprovedAt() *ConsultationRequestUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *ConsultationRequestUpdate) SetRejectedAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableRejectedAt(v *time.Time) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *ConsultationRequestUpdate) ClearRejectedAt() *ConsultationRequestUpdate {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ConsultationRequestUpdate) SetExpiresAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableExpiresAt(v *time.Time) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ConsultationRequestUpdate) ClearExpiresAt() *ConsultationRequestUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetOwnerResponseDueAt sets the "owner_response_due_at" field.
func (_u *ConsultationRequestUpdate) SetOwnerResponseDueAt(v time.Time) *ConsultationRequestUpdate {
	_u.mutation.SetOwnerResponseDueAt(v)
	return _u
}

// SetNillableOwnerResponseDueAt sets the "owner_response_due_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableOwnerResponseDueAt(v *time.Time) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetOwnerResponseDueAt(*v)
	}
	return _u
}

// ClearOwnerResponseDueAt clears the value of the "owner_response_due_at" field.
func (_u *ConsultationRequestUpdate) ClearOwnerResponseDueAt() *ConsultationRequestUpdate {
	_u.mutation.ClearOwnerResponseDueAt()
	return _u
}

// SetReminderCount sets the "reminder_count" field.
func (_u *ConsultationRequestUpdate) SetReminderCount(v int) *ConsultationRequestUpdate {
	_u.mutation.ResetReminderCount()
	_u.mutation.SetReminderCount(v)
	return _u
}

// SetNillableReminderCount sets the "reminder_count" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableReminderCount(v *int) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetReminderCount(*v)
	}
	return _u
}

// AddReminderCount adds value to the "reminder_count" field.
func (_u *ConsultationRequestUpdate) AddReminderCount(v int) *ConsultationRequestUpdate {
	_u.mutation.AddReminderCount(v)
	return _u
}

// SetAutoClosedReason sets the "auto_closed_reason" field.
func (_u *ConsultationRequestUpdate) SetAutoClosedReason(v string) *ConsultationRequestUpdate {
	_u.mutation.SetAutoClosedReason(v)
	return _u
}

// SetNillableAutoClosedReason sets the "auto_closed_reason" field if the given value is not nil.
func (_u *ConsultationRequestUpdate) SetNillableAutoClosedReason(v *string) *ConsultationRequestUpdate {
	if v != nil {
		_u.SetAutoClosedReason(*v)
	}
	return _u
}

// ClearAutoClosedReason clears the value of the "auto_closed_reason" field.
func (_u *ConsultationRequestUpdate) ClearAutoClosedReason() *ConsultationRequestUpdate {
	_u.mutation.ClearAutoClosedReason()
	return _u
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_u *ConsultationRequestUpdate) SetValidationCase(v *ValidationCase) *ConsultationRequestUpdate {
	return _u.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_u *ConsultationRequestUpdate) SetValidatorUser(v *User) *ConsultationRequestUpdate {
	return _u.SetValidatorUserID(v.ID)
}

// Mutation returns the ConsultationRequestMutation object of the builder.
func (_u *ConsultationRequestUpdate) Mutation() *ConsultationRequestMutation {
	return _u.mutation
}

// ClearValidationCase clears the "validation_case" edge to the ValidationCase entity.
func (_u *ConsultationRequestUpdate) ClearValidationCase() *ConsultationRequestUpdate {
	_u.mutation.ClearValidationCase()
	return _u
}

// ClearValidatorUser clears the "validator_user" edge to the User entity.
func (_u *ConsultationRequestUpdate) ClearValidatorUser() *ConsultationRequestUpdate {
	_u.mutation.ClearValidatorUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConsultationRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConsultationRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConsultationRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConsultationRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConsultationRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := consultationrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConsultationRequestUpdate) check() error {
	if v, ok := _u.mutation.ValidationCaseID(); ok {
		if err := consultationrequest.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validation_case_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidatorUserID(); ok {
		if err := consultationrequest.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validator_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := consultationrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReminderCount(); ok {
		if err := consultationrequest.ReminderCountValidator(v); err != nil {
			return &ValidationError{Name: "reminder_count", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.reminder_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AutoClosedReason(); ok {
		if err := consultationrequest.AutoClosedReasonValidator(v); err != nil {
			return &ValidationError{Name: "auto_closed_reason", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.auto_closed_reason": %w`, err)}
		}
	}
	if _u.mutation.ValidationCaseCleared() && len(_u.mutation.ValidationCaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsultationRequest.validation_case"`)
	}
	if _u.mutation.ValidatorUserCleared() && len(_u.mutation.ValidatorUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsultationRequest.validator_user"`)
	}
	return nil
}

func (_u *ConsultationRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consultationrequest.Table, consultationrequest.Columns, sqlgraph.NewFieldSpec(consultationrequest.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(consultationrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(consultationrequest.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(consultationrequest.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(consultationrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(consultationrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(consultationrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(consultationrequest.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(consultationrequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(consultationrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(consultationrequest.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerResponseDueAt(); ok {
		_spec.SetField(consultationrequest.FieldOwnerResponseDueAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerResponseDueAtCleared() {
		_spec.ClearField(consultationrequest.FieldOwnerResponseDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReminderCount(); ok {
		_spec.SetField(consultationrequest.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReminderCount(); ok {
		_spec.AddField(consultationrequest.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoClosedReason(); ok {
		_spec.SetField(consultationrequest.FieldAutoClosedReason, field.TypeString, value)
	}
	if _u.mutation.AutoClosedReasonCleared() {
		_spec.ClearField(consultationrequest.FieldAutoClosedReason, field.TypeString)
	}
	if _u.mutation.ValidationCaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidationCaseTable,
			Columns: []string{consultationrequest.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidationCaseTable,
			Columns: []string{consultationrequest.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ValidatorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidatorUserTable,
			Columns: []string{consultationrequest.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidatorUserTable,
			Columns: []string{consultationrequest.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consultationrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConsultationRequestUpdateOne is the builder for updating a single ConsultationRequest entity.
type ConsultationRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConsultationRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConsultationRequestUpdateOne) SetUpdatedAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ConsultationRequestUpdateOne) SetDeletedAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableDeletedAt(v *time.Time) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ConsultationRequestUpdateOne) ClearDeletedAt() *ConsultationRequestUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_u *ConsultationRequestUpdateOne) SetValidationCaseID(v int) *ConsultationRequestUpdateOne {
	_u.mutation.SetValidationCaseID(v)
	return _u
}

// SetNillableValidationCaseID sets the "validation_case_id" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableValidationCaseID(v *int) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetValidationCaseID(*v)
	}
	return _u
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_u *ConsultationRequestUpdateOne) SetValidatorUserID(v int) *ConsultationRequestUpdateOne {
	_u.mutation.SetValidatorUserID(v)
	return _u
}

// SetNillableValidatorUserID sets the "validator_user_id" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableValidatorUserID(v *int) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetValidatorUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConsultationRequestUpdateOne) SetStatus(v string) *ConsultationRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableStatus(v *string) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *ConsultationRequestUpdateOne) SetApprovedAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableApprovedAt(v *time.Time) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *ConsultationRequestUpdateOne) ClearApprovedAt() *ConsultationRequestUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *ConsultationRequestUpdateOne) SetRejectedAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableRejectedAt(v *time.Time) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *ConsultationRequestUpdateOne) ClearRejectedAt() *ConsultationRequestUpdateOne {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ConsultationRequestUpdateOne) SetExpiresAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ConsultationRequestUpdateOne) ClearExpiresAt() *ConsultationRequestUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetOwnerResponseDueAt sets the "owner_response_due_at" field.
func (_u *ConsultationRequestUpdateOne) SetOwnerResponseDueAt(v time.Time) *ConsultationRequestUpdateOne {
	_u.mutation.SetOwnerResponseDueAt(v)
	return _u
}

// SetNillableOwnerResponseDueAt sets the "owner_response_due_at" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableOwnerResponseDueAt(v *time.Time) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetOwnerResponseDueAt(*v)
	}
	return _u
}

// ClearOwnerResponseDueAt clears the value of the "owner_response_due_at" field.
func (_u *ConsultationRequestUpdateOne) ClearOwnerResponseDueAt() *ConsultationRequestUpdateOne {
	_u.mutation.ClearOwnerResponseDueAt()
	return _u
}

// SetReminderCount sets the "reminder_count" field.
func (_u *ConsultationRequestUpdateOne) SetReminderCount(v int) *ConsultationRequestUpdateOne {
	_u.mutation.ResetReminderCount()
	_u.mutation.SetReminderCount(v)
	return _u
}

// SetNillableReminderCount sets the "reminder_count" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableReminderCount(v *int) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetReminderCount(*v)
	}
	return _u
}

// AddReminderCount adds value to the "reminder_count" field.
func (_u *ConsultationRequestUpdateOne) AddReminderCount(v int) *ConsultationRequestUpdateOne {
	_u.mutation.AddReminderCount(v)
	return _u
}

// SetAutoClosedReason sets the "auto_closed_reason" field.
func (_u *ConsultationRequestUpdateOne) SetAutoClosedReason(v string) *ConsultationRequestUpdateOne {
	_u.mutation.SetAutoClosedReason(v)
	return _u
}

// SetNillableAutoClosedReason sets the "auto_closed_reason" field if the given value is not nil.
func (_u *ConsultationRequestUpdateOne) SetNillableAutoClosedReason(v *string) *ConsultationRequestUpdateOne {
	if v != nil {
		_u.SetAutoClosedReason(*v)
	}
	return _u
}

// ClearAutoClosedReason clears the value of the "auto_closed_reason" field.
func (_u *ConsultationRequestUpdateOne) ClearAutoClosedReason() *ConsultationRequestUpdateOne {
	_u.mutation.ClearAutoClosedReason()
	return _u
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_u *ConsultationRequestUpdateOne) SetValidationCase(v *ValidationCase) *ConsultationRequestUpdateOne {
	return _u.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_u *ConsultationRequestUpdateOne) SetValidatorUser(v *User) *ConsultationRequestUpdateOne {
	return _u.SetValidatorUserID(v.ID)
}

// Mutation returns the ConsultationRequestMutation object of the builder.
func (_u *ConsultationRequestUpdateOne) Mutation() *ConsultationRequestMutation {
	return _u.mutation
}

// ClearValidationCase clears the "validation_case" edge to the ValidationCase entity.
func (_u *ConsultationRequestUpdateOne) ClearValidationCase() *ConsultationRequestUpdateOne {
	_u.mutation.ClearValidationCase()
	return _u
}

// ClearValidatorUser clears the "validator_user" edge to the User entity.
func (_u *ConsultationRequestUpdateOne) ClearValidatorUser() *ConsultationRequestUpdateOne {
	_u.mutation.ClearValidatorUser()
	return _u
}

// Where appends a list predicates to the ConsultationRequestUpdate builder.
func (_u *ConsultationRequestUpdateOne) Where(ps ...predicate.ConsultationRequest) *ConsultationRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConsultationRequestUpdateOne) Select(field string, fields ...string) *ConsultationRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConsultationRequest entity.
func (_u *ConsultationRequestUpdateOne) Save(ctx context.Context) (*ConsultationRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConsultationRequestUpdateOne) SaveX(ctx context.Context) *ConsultationRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConsultationRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConsultationRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConsultationRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := consultationrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConsultationRequestUpdateOne) check() error {
	if v, ok := _u.mutation.ValidationCaseID(); ok {
		if err := consultationrequest.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validation_case_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidatorUserID(); ok {
		if err := consultationrequest.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validator_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := consultationrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReminderCount(); ok {
		if err := consultationrequest.ReminderCountValidator(v); err != nil {
			return &ValidationError{Name: "reminder_count", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.reminder_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AutoClosedReason(); ok {
		if err := consultationrequest.AutoClosedReasonValidator(v); err != nil {
			return &ValidationError{Name: "auto_closed_reason", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.auto_closed_reason": %w`, err)}
		}
	}
	if _u.mutation.ValidationCaseCleared() && len(_u.mutation.ValidationCaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsultationRequest.validation_case"`)
	}
	if _u.mutation.ValidatorUserCleared() && len(_u.mutation.ValidatorUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsultationRequest.validator_user"`)
	}
	return nil
}

func (_u *ConsultationRequestUpdateOne) sqlSave(ctx context.Context) (_node *ConsultationRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consultationrequest.Table, consultationrequest.Columns, sqlgraph.NewFieldSpec(consultationrequest.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConsultationRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consultationrequest.FieldID)
		for _, f := range fields {
			if !consultationrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != consultationrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(consultationrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(consultationrequest.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(consultationrequest.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(consultationrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(consultationrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(consultationrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(consultationrequest.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(consultationrequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(consultationrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(consultationrequest.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerResponseDueAt(); ok {
		_spec.SetField(consultationrequest.FieldOwnerResponseDueAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerResponseDueAtCleared() {
		_spec.ClearField(consultationrequest.FieldOwnerResponseDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReminderCount(); ok {
		_spec.SetField(consultationrequest.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReminderCount(); ok {
		_spec.AddField(consultationrequest.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoClosedReason(); ok {
		_spec.SetField(consultationrequest.FieldAutoClosedReason, field.TypeString, value)
	}
	if _u.mutation.AutoClosedReasonCleared() {
		_spec.ClearField(consultationrequest.FieldAutoClosedReason, field.TypeString)
	}
	if _u.mutation.ValidationCaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidationCaseTable,
			Columns: []string{consultationrequest.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidationCaseTable,
			Columns: []string{consultationrequest.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ValidatorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidatorUserTable,
			Columns: []string{consultationrequest.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidatorUserTable,
			Columns: []string{consultationrequest.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConsultationRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consultationrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
