// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/consultationrequest"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConsultationRequestCreate is the builder for creating a ConsultationRequest entity.
type ConsultationRequestCreate struct {
	config
	mutation *ConsultationRequestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConsultationRequestCreate) SetCreatedAt(v time.Time) *ConsultationRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableCreatedAt(v *time.Time) *ConsultationRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConsultationRequestCreate) SetUpdatedAt(v time.Time) *ConsultationRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableUpdatedAt(v *time.Time) *ConsultationRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ConsultationRequestCreate) SetDeletedAt(v time.Time) *ConsultationRequestCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableDeletedAt(v *time.Time) *ConsultationRequestCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_c *ConsultationRequestCreate) SetValidationCaseID(v int) *ConsultationRequestCreate {
	_c.mutation.SetValidationCaseID(v)
	return _c
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_c *ConsultationRequestCreate) SetValidatorUserID(v int) *ConsultationRequestCreate {
	_c.mutation.SetValidatorUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConsultationRequestCreate) SetStatus(v string) *ConsultationRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableStatus(v *string) *ConsultationRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *ConsultationRequestCreate) SetApprovedAt(v time.Time) *ConsultationRequestCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableApprovedAt(v *time.Time) *ConsultationRequestCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetRejectedAt sets the "rejected_at" field.
func (_c *ConsultationRequestCreate) SetRejectedAt(v time.Time) *ConsultationRequestCreate {
	_c.mutation.SetRejectedAt(v)
	return _c
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_c *ConsultationRequestCreate) SetNillableRejectedAt(v *time.Time) *ConsultationRequestCreate {
	if v != nil {
		_c.SetRejectedAt(*v)
	}
	return _c
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_c *ConsultationRequestCreate) SetValidationCase(v *ValidationCase) *ConsultationRequestCreate {
	return _c.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_c *ConsultationRequestCreate) SetValidatorUser(v *User) *ConsultationRequestCreate {
	return _c.SetValidatorUserID(v.ID)
}

// Mutation returns the ConsultationRequestMutation object of the builder.
func (_c *ConsultationRequestCreate) Mutation() *ConsultationRequestMutation {
	return _c.mutation
}

// Save creates the ConsultationRequest in the database.
func (_c *ConsultationRequestCreate) Save(ctx context.Context) (*ConsultationRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConsultationRequestCreate) SaveX(ctx context.Context) *ConsultationRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConsultationRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConsultationRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConsultationRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := consultationrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := consultationrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := consultationrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConsultationRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConsultationRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConsultationRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.ValidationCaseID(); !ok {
		return &ValidationError{Name: "validation_case_id", err: errors.New(`ent: missing required field "ConsultationRequest.validation_case_id"`)}
	}
	if v, ok := _c.mutation.ValidationCaseID(); ok {
		if err := consultationrequest.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validation_case_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidatorUserID(); !ok {
		return &ValidationError{Name: "validator_user_id", err: errors.New(`ent: missing required field "ConsultationRequest.validator_user_id"`)}
	}
	if v, ok := _c.mutation.ValidatorUserID(); ok {
		if err := consultationrequest.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.validator_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ConsultationRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := consultationrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConsultationRequest.status": %w`, err)}
		}
	}
	if len(_c.mutation.ValidationCaseIDs()) == 0 {
		return &ValidationError{Name: "validation_case", err: errors.New(`ent: missing required edge "ConsultationRequest.validation_case"`)}
	}
	if len(_c.mutation.ValidatorUserIDs()) == 0 {
		return &ValidationError{Name: "validator_user", err: errors.New(`ent: missing required edge "ConsultationRequest.validator_user"`)}
	}
	return nil
}

func (_c *ConsultationRequestCreate) sqlSave(ctx context.Context) (*ConsultationRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConsultationRequestCreate) createSpec() (*ConsultationRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &ConsultationRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(consultationrequest.Table, sqlgraph.NewFieldSpec(consultationrequest.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(consultationrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(consultationrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(consultationrequest.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(consultationrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(consultationrequest.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.RejectedAt(); ok {
		_spec.SetField(consultationrequest.FieldRejectedAt, field.TypeTime, value)
		_node.RejectedAt = &value
	}
	if nodes := _c.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidationCaseTable,
			Columns: []string{consultationrequest.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidationCaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultationrequest.ValidatorUserTable,
			Columns: []string{consultationrequest.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidatorUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConsultationRequestCreateBulk is the builder for creating many ConsultationRequest entities in bulk.
type ConsultationRequestCreateBulk struct {
	config
	err      error
	builders []*ConsultationRequestCreate
}

// Save creates the ConsultationRequest entities in the database.
func (_c *ConsultationRequestCreateBulk) Save(ctx context.Context) ([]*ConsultationRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConsultationRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConsultationRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConsultationRequestCreateBulk) SaveX(ctx context.Context) []*ConsultationRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConsultationRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConsultationRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
