// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/endorsement"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EndorsementCreate is the builder for creating a Endorsement entity.
type EndorsementCreate struct {
	config
	mutation *EndorsementMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EndorsementCreate) SetCreatedAt(v time.Time) *EndorsementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableCreatedAt(v *time.Time) *EndorsementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EndorsementCreate) SetUpdatedAt(v time.Time) *EndorsementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableUpdatedAt(v *time.Time) *EndorsementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EndorsementCreate) SetDeletedAt(v time.Time) *EndorsementCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableDeletedAt(v *time.Time) *EndorsementCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_c *EndorsementCreate) SetValidationCaseID(v int) *EndorsementCreate {
	_c.mutation.SetValidationCaseID(v)
	return _c
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_c *EndorsementCreate) SetValidatorUserID(v int) *EndorsementCreate {
	_c.mutation.SetValidatorUserID(v)
	return _c
}

// SetCertifiedArtifactDocumentID sets the "certified_artifact_document_id" field.
func (_c *EndorsementCreate) SetCertifiedArtifactDocumentID(v string) *EndorsementCreate {
	_c.mutation.SetCertifiedArtifactDocumentID(v)
	return _c
}

// SetNillableCertifiedArtifactDocumentID sets the "certified_artifact_document_id" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableCertifiedArtifactDocumentID(v *string) *EndorsementCreate {
	if v != nil {
		_c.SetCertifiedArtifactDocumentID(*v)
	}
	return _c
}

// SetStance sets the "stance" field.
func (_c *EndorsementCreate) SetStance(v string) *EndorsementCreate {
	_c.mutation.SetStance(v)
	return _c
}

// SetNillableStance sets the "stance" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableStance(v *string) *EndorsementCreate {
	if v != nil {
		_c.SetStance(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *EndorsementCreate) SetNote(v string) *EndorsementCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *EndorsementCreate) SetNillableNote(v *string) *EndorsementCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_c *EndorsementCreate) SetValidationCase(v *ValidationCase) *EndorsementCreate {
	return _c.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_c *EndorsementCreate) SetValidatorUser(v *User) *EndorsementCreate {
	return _c.SetValidatorUserID(v.ID)
}

// Mutation returns the EndorsementMutation object of the builder.
func (_c *EndorsementCreate) Mutation() *EndorsementMutation {
	return _c.mutation
}

// Save creates the Endorsement in the database.
func (_c *EndorsementCreate) Save(ctx context.Context) (*Endorsement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EndorsementCreate) SaveX(ctx context.Context) *Endorsement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndorsementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndorsementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EndorsementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := endorsement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := endorsement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Stance(); !ok {
		v := endorsement.DefaultStance
		_c.mutation.SetStance(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := endorsement.DefaultNote
		_c.mutation.SetNote(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EndorsementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Endorsement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Endorsement.updated_at"`)}
	}
	if _, ok := _c.mutation.ValidationCaseID(); !ok {
		return &ValidationError{Name: "validation_case_id", err: errors.New(`ent: missing required field "Endorsement.validation_case_id"`)}
	}
	if v, ok := _c.mutation.ValidationCaseID(); ok {
		if err := endorsement.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "Endorsement.validation_case_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidatorUserID(); !ok {
		return &ValidationError{Name: "validator_user_id", err: errors.New(`ent: missing required field "Endorsement.validator_user_id"`)}
	}
	if v, ok := _c.mutation.ValidatorUserID(); ok {
		if err := endorsement.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "Endorsement.validator_user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Stance(); ok {
		if err := endorsement.StanceValidator(v); err != nil {
			return &ValidationError{Name: "stance", err: fmt.Errorf(`ent: validator failed for field "Endorsement.stance": %w`, err)}
		}
	}
	if len(_c.mutation.ValidationCaseIDs()) == 0 {
		return &ValidationError{Name: "validation_case", err: errors.New(`ent: missing required edge "Endorsement.validation_case"`)}
	}
	if len(_c.mutation.ValidatorUserIDs()) == 0 {
		return &ValidationError{Name: "validator_user", err: errors.New(`ent: missing required edge "Endorsement.validator_user"`)}
	}
	return nil
}

func (_c *EndorsementCreate) sqlSave(ctx context.Context) (*Endorsement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EndorsementCreate) createSpec() (*Endorsement, *sqlgraph.CreateSpec) {
	var (
		_node = &Endorsement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(endorsement.Table, sqlgraph.NewFieldSpec(endorsement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(endorsement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(endorsement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(endorsement.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CertifiedArtifactDocumentID(); ok {
		_spec.SetField(endorsement.FieldCertifiedArtifactDocumentID, field.TypeString, value)
		_node.CertifiedArtifactDocumentID = &value
	}
	if value, ok := _c.mutation.Stance(); ok {
		_spec.SetField(endorsement.FieldStance, field.TypeString, value)
		_node.Stance = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(endorsement.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := _c.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endorsement.ValidationCaseTable,
			Columns: []string{endorsement.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidationCaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endorsement.ValidatorUserTable,
			Columns: []string{endorsement.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidatorUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EndorsementCreateBulk is the builder for creating many Endorsement entities in bulk.
type EndorsementCreateBulk struct {
	config
	err      error
	builders []*EndorsementCreate
}

// Save creates the Endorsement entities in the database.
func (_c *EndorsementCreateBulk) Save(ctx context.Context) ([]*Endorsement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Endorsement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EndorsementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EndorsementCreateBulk) SaveX(ctx context.Context) []*Endorsement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndorsementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndorsementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
