// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/featureflag"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeatureFlagCreate is the builder for creating a FeatureFlag entity.
type FeatureFlagCreate struct {
	config
	mutation *FeatureFlagMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeatureFlagCreate) SetCreatedAt(v time.Time) *FeatureFlagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableCreatedAt(v *time.Time) *FeatureFlagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FeatureFlagCreate) SetUpdatedAt(v time.Time) *FeatureFlagCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableUpdatedAt(v *time.Time) *FeatureFlagCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FeatureFlagCreate) SetDeletedAt(v time.Time) *FeatureFlagCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableDeletedAt(v *time.Time) *FeatureFlagCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *FeatureFlagCreate) SetKey(v string) *FeatureFlagCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *FeatureFlagCreate) SetEnabled(v bool) *FeatureFlagCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableEnabled(v *bool) *FeatureFlagCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *FeatureFlagCreate) SetDescription(v string) *FeatureFlagCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableDescription(v *string) *FeatureFlagCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRolloutPercentage sets the "rollout_percentage" field.
func (_c *FeatureFlagCreate) SetRolloutPercentage(v int) *FeatureFlagCreate {
	_c.mutation.SetRolloutPercentage(v)
	return _c
}

// SetNillableRolloutPercentage sets the "rollout_percentage" field if the given value is not nil.
func (_c *FeatureFlagCreate) SetNillableRolloutPercentage(v *int) *FeatureFlagCreate {
	if v != nil {
		_c.SetRolloutPercentage(*v)
	}
	return _c
}

// Mutation returns the FeatureFlagMutation object of the builder.
func (_c *FeatureFlagCreate) Mutation() *FeatureFlagMutation {
	return _c.mutation
}

// Save creates the FeatureFlag in the database.
func (_c *FeatureFlagCreate) Save(ctx context.Context) (*FeatureFlag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeatureFlagCreate) SaveX(ctx context.Context) *FeatureFlag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureFlagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureFlagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeatureFlagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := featureflag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := featureflag.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := featureflag.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RolloutPercentage(); !ok {
		v := featureflag.DefaultRolloutPercentage
		_c.mutation.SetRolloutPercentage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeatureFlagCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FeatureFlag.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FeatureFlag.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "FeatureFlag.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := featureflag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "FeatureFlag.enabled"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := featureflag.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RolloutPercentage(); !ok {
		return &ValidationError{Name: "rollout_percentage", err: errors.New(`ent: missing required field "FeatureFlag.rollout_percentage"`)}
	}
	if v, ok := _c.mutation.RolloutPercentage(); ok {
		if err := featureflag.RolloutPercentageValidator(v); err != nil {
			return &ValidationError{Name: "rollout_percentage", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.rollout_percentage": %w`, err)}
		}
	}
	return nil
}

func (_c *FeatureFlagCreate) sqlSave(ctx context.Context) (*FeatureFlag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeatureFlagCreate) createSpec() (*FeatureFlag, *sqlgraph.CreateSpec) {
	var (
		_node = &FeatureFlag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(featureflag.Table, sqlgraph.NewFieldSpec(featureflag.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(featureflag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(featureflag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(featureflag.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(featureflag.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(featureflag.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(featureflag.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RolloutPercentage(); ok {
		_spec.SetField(featureflag.FieldRolloutPercentage, field.TypeInt, value)
		_node.RolloutPercentage = value
	}
	return _node, _spec
}

// FeatureFlagCreateBulk is the builder for creating many FeatureFlag entities in bulk.
type FeatureFlagCreateBulk struct {
	config
	err      error
	builders []*FeatureFlagCreate
}

// Save creates the FeatureFlag entities in the database.
func (_c *FeatureFlagCreateBulk) Save(ctx context.Context) ([]*FeatureFlag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FeatureFlag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeatureFlagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeatureFlagCreateBulk) SaveX(ctx context.Context) []*FeatureFlag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureFlagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureFlagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
