// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/finaloffer"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FinalOfferCreate is the builder for creating a FinalOffer entity.
type FinalOfferCreate struct {
	config
	mutation *FinalOfferMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinalOfferCreate) SetCreatedAt(v time.Time) *FinalOfferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableCreatedAt(v *time.Time) *FinalOfferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FinalOfferCreate) SetUpdatedAt(v time.Time) *FinalOfferCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableUpdatedAt(v *time.Time) *FinalOfferCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FinalOfferCreate) SetDeletedAt(v time.Time) *FinalOfferCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableDeletedAt(v *time.Time) *FinalOfferCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetValidationCaseID sets the "validation_case_id" field.
func (_c *FinalOfferCreate) SetValidationCaseID(v int) *FinalOfferCreate {
	_c.mutation.SetValidationCaseID(v)
	return _c
}

// SetValidatorUserID sets the "validator_user_id" field.
func (_c *FinalOfferCreate) SetValidatorUserID(v int) *FinalOfferCreate {
	_c.mutation.SetValidatorUserID(v)
	return _c
}

// SetSubmissionKey sets the "submission_key" field.
func (_c *FinalOfferCreate) SetSubmissionKey(v string) *FinalOfferCreate {
	_c.mutation.SetSubmissionKey(v)
	return _c
}

// SetNillableSubmissionKey sets the "submission_key" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableSubmissionKey(v *string) *FinalOfferCreate {
	if v != nil {
		_c.SetSubmissionKey(*v)
	}
	return _c
}

// SetWorkflowCycle sets the "workflow_cycle" field.
func (_c *FinalOfferCreate) SetWorkflowCycle(v int) *FinalOfferCreate {
	_c.mutation.SetWorkflowCycle(v)
	return _c
}

// SetNillableWorkflowCycle sets the "workflow_cycle" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableWorkflowCycle(v *int) *FinalOfferCreate {
	if v != nil {
		_c.SetWorkflowCycle(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *FinalOfferCreate) SetAmount(v int64) *FinalOfferCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetHoldHours sets the "hold_hours" field.
func (_c *FinalOfferCreate) SetHoldHours(v int) *FinalOfferCreate {
	_c.mutation.SetHoldHours(v)
	return _c
}

// SetNillableHoldHours sets the "hold_hours" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableHoldHours(v *int) *FinalOfferCreate {
	if v != nil {
		_c.SetHoldHours(*v)
	}
	return _c
}

// SetTerms sets the "terms" field.
func (_c *FinalOfferCreate) SetTerms(v string) *FinalOfferCreate {
	_c.mutation.SetTerms(v)
	return _c
}

// SetNillableTerms sets the "terms" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableTerms(v *string) *FinalOfferCreate {
	if v != nil {
		_c.SetTerms(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FinalOfferCreate) SetStatus(v string) *FinalOfferCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableStatus(v *string) *FinalOfferCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *FinalOfferCreate) SetAcceptedAt(v time.Time) *FinalOfferCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableAcceptedAt(v *time.Time) *FinalOfferCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetRejectedAt sets the "rejected_at" field.
func (_c *FinalOfferCreate) SetRejectedAt(v time.Time) *FinalOfferCreate {
	_c.mutation.SetRejectedAt(v)
	return _c
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_c *FinalOfferCreate) SetNillableRejectedAt(v *time.Time) *FinalOfferCreate {
	if v != nil {
		_c.SetRejectedAt(*v)
	}
	return _c
}

// SetValidationCase sets the "validation_case" edge to the ValidationCase entity.
func (_c *FinalOfferCreate) SetValidationCase(v *ValidationCase) *FinalOfferCreate {
	return _c.SetValidationCaseID(v.ID)
}

// SetValidatorUser sets the "validator_user" edge to the User entity.
func (_c *FinalOfferCreate) SetValidatorUser(v *User) *FinalOfferCreate {
	return _c.SetValidatorUserID(v.ID)
}

// Mutation returns the FinalOfferMutation object of the builder.
func (_c *FinalOfferCreate) Mutation() *FinalOfferMutation {
	return _c.mutation
}

// Save creates the FinalOffer in the database.
func (_c *FinalOfferCreate) Save(ctx context.Context) (*FinalOffer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinalOfferCreate) SaveX(ctx context.Context) *FinalOffer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinalOfferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinalOfferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinalOfferCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := finaloffer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := finaloffer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.WorkflowCycle(); !ok {
		v := finaloffer.DefaultWorkflowCycle
		_c.mutation.SetWorkflowCycle(v)
	}
	if _, ok := _c.mutation.HoldHours(); !ok {
		v := finaloffer.DefaultHoldHours
		_c.mutation.SetHoldHours(v)
	}
	if _, ok := _c.mutation.Terms(); !ok {
		v := finaloffer.DefaultTerms
		_c.mutation.SetTerms(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := finaloffer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinalOfferCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FinalOffer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FinalOffer.updated_at"`)}
	}
	if _, ok := _c.mutation.ValidationCaseID(); !ok {
		return &ValidationError{Name: "validation_case_id", err: errors.New(`ent: missing required field "FinalOffer.validation_case_id"`)}
	}
	if v, ok := _c.mutation.ValidationCaseID(); ok {
		if err := finaloffer.ValidationCaseIDValidator(v); err != nil {
			return &ValidationError{Name: "validation_case_id", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.validation_case_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidatorUserID(); !ok {
		return &ValidationError{Name: "validator_user_id", err: errors.New(`ent: missing required field "FinalOffer.validator_user_id"`)}
	}
	if v, ok := _c.mutation.ValidatorUserID(); ok {
		if err := finaloffer.ValidatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "validator_user_id", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.validator_user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SubmissionKey(); ok {
		if err := finaloffer.SubmissionKeyValidator(v); err != nil {
			return &ValidationError{Name: "submission_key", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.submission_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkflowCycle(); !ok {
		return &ValidationError{Name: "workflow_cycle", err: errors.New(`ent: missing required field "FinalOffer.workflow_cycle"`)}
	}
	if v, ok := _c.mutation.WorkflowCycle(); ok {
		if err := finaloffer.WorkflowCycleValidator(v); err != nil {
			return &ValidationError{Name: "workflow_cycle", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.workflow_cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "FinalOffer.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := finaloffer.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HoldHours(); !ok {
		return &ValidationError{Name: "hold_hours", err: errors.New(`ent: missing required field "FinalOffer.hold_hours"`)}
	}
	if v, ok := _c.mutation.HoldHours(); ok {
		if err := finaloffer.HoldHoursValidator(v); err != nil {
			return &ValidationError{Name: "hold_hours", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.hold_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FinalOffer.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := finaloffer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FinalOffer.status": %w`, err)}
		}
	}
	if len(_c.mutation.ValidationCaseIDs()) == 0 {
		return &ValidationError{Name: "validation_case", err: errors.New(`ent: missing required edge "FinalOffer.validation_case"`)}
	}
	if len(_c.mutation.ValidatorUserIDs()) == 0 {
		return &ValidationError{Name: "validator_user", err: errors.New(`ent: missing required edge "FinalOffer.validator_user"`)}
	}
	return nil
}

func (_c *FinalOfferCreate) sqlSave(ctx context.Context) (*FinalOffer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinalOfferCreate) createSpec() (*FinalOffer, *sqlgraph.CreateSpec) {
	var (
		_node = &FinalOffer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(finaloffer.Table, sqlgraph.NewFieldSpec(finaloffer.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(finaloffer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(finaloffer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(finaloffer.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.SubmissionKey(); ok {
		_spec.SetField(finaloffer.FieldSubmissionKey, field.TypeString, value)
		_node.SubmissionKey = &value
	}
	if value, ok := _c.mutation.WorkflowCycle(); ok {
		_spec.SetField(finaloffer.FieldWorkflowCycle, field.TypeInt, value)
		_node.WorkflowCycle = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(finaloffer.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.HoldHours(); ok {
		_spec.SetField(finaloffer.FieldHoldHours, field.TypeInt, value)
		_node.HoldHours = value
	}
	if value, ok := _c.mutation.Terms(); ok {
		_spec.SetField(finaloffer.FieldTerms, field.TypeString, value)
		_node.Terms = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(finaloffer.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(finaloffer.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.RejectedAt(); ok {
		_spec.SetField(finaloffer.FieldRejectedAt, field.TypeTime, value)
		_node.RejectedAt = &value
	}
	if nodes := _c.mutation.ValidationCaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   finaloffer.ValidationCaseTable,
			Columns: []string{finaloffer.ValidationCaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(validationcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidationCaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ValidatorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   finaloffer.ValidatorUserTable,
			Columns: []string{finaloffer.ValidatorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ValidatorUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FinalOfferCreateBulk is the builder for creating many FinalOffer entities in bulk.
type FinalOfferCreateBulk struct {
	config
	err      error
	builders []*FinalOfferCreate
}

// Save creates the FinalOffer entities in the database.
func (_c *FinalOfferCreateBulk) Save(ctx context.Context) ([]*FinalOffer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinalOffer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinalOfferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinalOfferCreateBulk) SaveX(ctx context.Context) []*FinalOffer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinalOfferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinalOfferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
