// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/marketpurchaseorderstep"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MarketPurchaseOrderStep is the model entity for the MarketPurchaseOrderStep schema.
type MarketPurchaseOrderStep struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID string `json:"order_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// At holds the value of the "at" field.
	At           time.Time `json:"at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MarketPurchaseOrderStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case marketpurchaseorderstep.FieldID:
			values[i] = new(sql.NullInt64)
		case marketpurchaseorderstep.FieldOrderID, marketpurchaseorderstep.FieldCode, marketpurchaseorderstep.FieldLabel, marketpurchaseorderstep.FieldStatus, marketpurchaseorderstep.FieldMessage:
			values[i] = new(sql.NullString)
		case marketpurchaseorderstep.FieldCreatedAt, marketpurchaseorderstep.FieldUpdatedAt, marketpurchaseorderstep.FieldDeletedAt, marketpurchaseorderstep.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MarketPurchaseOrderStep fields.
func (_m *MarketPurchaseOrderStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case marketpurchaseorderstep.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case marketpurchaseorderstep.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case marketpurchaseorderstep.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case marketpurchaseorderstep.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case marketpurchaseorderstep.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case marketpurchaseorderstep.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case marketpurchaseorderstep.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case marketpurchaseorderstep.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case marketpurchaseorderstep.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case marketpurchaseorderstep.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				_m.At = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MarketPurchaseOrderStep.
// This includes values selected through modifiers, order, etc.
func (_m *MarketPurchaseOrderStep) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MarketPurchaseOrderStep.
// Note that you need to call MarketPurchaseOrderStep.Unwrap() before calling this method if this MarketPurchaseOrderStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MarketPurchaseOrderStep) Update() *MarketPurchaseOrderStepUpdateOne {
	return NewMarketPurchaseOrderStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MarketPurchaseOrderStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MarketPurchaseOrderStep) Unwrap() *MarketPurchaseOrderStep {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MarketPurchaseOrderStep is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MarketPurchaseOrderStep) String() string {
	var builder strings.Builder
	builder.WriteString("MarketPurchaseOrderStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("at=")
	builder.WriteString(_m.At.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MarketPurchaseOrderSteps is a parsable slice of MarketPurchaseOrderStep.
type MarketPurchaseOrderSteps []*MarketPurchaseOrderStep
