// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/thread"
	"backend-gin/ent/threadcredential"
	"backend-gin/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThreadCredentialCreate is the builder for creating a ThreadCredential entity.
type ThreadCredentialCreate struct {
	config
	mutation *ThreadCredentialMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThreadCredentialCreate) SetCreatedAt(v time.Time) *ThreadCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ThreadCredentialCreate) SetNillableCreatedAt(v *time.Time) *ThreadCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ThreadCredentialCreate) SetUpdatedAt(v time.Time) *ThreadCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ThreadCredentialCreate) SetNillableUpdatedAt(v *time.Time) *ThreadCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ThreadCredentialCreate) SetDeletedAt(v time.Time) *ThreadCredentialCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ThreadCredentialCreate) SetNillableDeletedAt(v *time.Time) *ThreadCredentialCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ThreadCredentialCreate) SetUserID(v int) *ThreadCredentialCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetThreadID sets the "thread_id" field.
func (_c *ThreadCredentialCreate) SetThreadID(v int) *ThreadCredentialCreate {
	_c.mutation.SetThreadID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ThreadCredentialCreate) SetUser(v *User) *ThreadCredentialCreate {
	return _c.SetUserID(v.ID)
}

// SetThread sets the "thread" edge to the Thread entity.
func (_c *ThreadCredentialCreate) SetThread(v *Thread) *ThreadCredentialCreate {
	return _c.SetThreadID(v.ID)
}

// Mutation returns the ThreadCredentialMutation object of the builder.
func (_c *ThreadCredentialCreate) Mutation() *ThreadCredentialMutation {
	return _c.mutation
}

// Save creates the ThreadCredential in the database.
func (_c *ThreadCredentialCreate) Save(ctx context.Context) (*ThreadCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThreadCredentialCreate) SaveX(ctx context.Context) *ThreadCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThreadCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := threadcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := threadcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThreadCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ThreadCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ThreadCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ThreadCredential.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := threadcredential.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ThreadCredential.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ThreadID(); !ok {
		return &ValidationError{Name: "thread_id", err: errors.New(`ent: missing required field "ThreadCredential.thread_id"`)}
	}
	if v, ok := _c.mutation.ThreadID(); ok {
		if err := threadcredential.ThreadIDValidator(v); err != nil {
			return &ValidationError{Name: "thread_id", err: fmt.Errorf(`ent: validator failed for field "ThreadCredential.thread_id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ThreadCredential.user"`)}
	}
	if len(_c.mutation.ThreadIDs()) == 0 {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "ThreadCredential.thread"`)}
	}
	return nil
}

func (_c *ThreadCredentialCreate) sqlSave(ctx context.Context) (*ThreadCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThreadCredentialCreate) createSpec() (*ThreadCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &ThreadCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(threadcredential.Table, sqlgraph.NewFieldSpec(threadcredential.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(threadcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(threadcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(threadcredential.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadcredential.UserTable,
			Columns: []string{threadcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadcredential.ThreadTable,
			Columns: []string{threadcredential.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThreadID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ThreadCredentialCreateBulk is the builder for creating many ThreadCredential entities in bulk.
type ThreadCredentialCreateBulk struct {
	config
	err      error
	builders []*ThreadCredentialCreate
}

// Save creates the ThreadCredential entities in the database.
func (_c *ThreadCredentialCreateBulk) Save(ctx context.Context) ([]*ThreadCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ThreadCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreadCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThreadCredentialCreateBulk) SaveX(ctx context.Context) []*ThreadCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
