// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/backupcode"
	"backend-gin/ent/badge"
	"backend-gin/ent/credential"
	"backend-gin/ent/devicefingerprint"
	"backend-gin/ent/deviceusermapping"
	"backend-gin/ent/emailverificationtoken"
	"backend-gin/ent/passkey"
	"backend-gin/ent/passwordresettoken"
	"backend-gin/ent/securityevent"
	"backend-gin/ent/session"
	"backend-gin/ent/sessionlock"
	"backend-gin/ent/sudosession"
	"backend-gin/ent/thread"
	"backend-gin/ent/totppendingtoken"
	"backend-gin/ent/user"
	"backend-gin/ent/userbadge"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserCreate) SetDeletedAt(v time.Time) *UserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableDeletedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsername(v *string) *UserCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetEmailVerified sets the "email_verified" field.
func (_c *UserCreate) SetEmailVerified(v bool) *UserCreate {
	_c.mutation.SetEmailVerified(v)
	return _c
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_c *UserCreate) SetNillableEmailVerified(v *bool) *UserCreate {
	if v != nil {
		_c.SetEmailVerified(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *UserCreate) SetAvatarURL(v string) *UserCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarURL(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *UserCreate) SetFullName(v string) *UserCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableFullName(v *string) *UserCreate {
	if v != nil {
		_c.SetFullName(*v)
	}
	return _c
}

// SetBio sets the "bio" field.
func (_c *UserCreate) SetBio(v string) *UserCreate {
	_c.mutation.SetBio(v)
	return _c
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_c *UserCreate) SetNillableBio(v *string) *UserCreate {
	if v != nil {
		_c.SetBio(*v)
	}
	return _c
}

// SetPronouns sets the "pronouns" field.
func (_c *UserCreate) SetPronouns(v string) *UserCreate {
	_c.mutation.SetPronouns(v)
	return _c
}

// SetNillablePronouns sets the "pronouns" field if the given value is not nil.
func (_c *UserCreate) SetNillablePronouns(v *string) *UserCreate {
	if v != nil {
		_c.SetPronouns(*v)
	}
	return _c
}

// SetCompany sets the "company" field.
func (_c *UserCreate) SetCompany(v string) *UserCreate {
	_c.mutation.SetCompany(v)
	return _c
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (_c *UserCreate) SetNillableCompany(v *string) *UserCreate {
	if v != nil {
		_c.SetCompany(*v)
	}
	return _c
}

// SetTelegram sets the "telegram" field.
func (_c *UserCreate) SetTelegram(v string) *UserCreate {
	_c.mutation.SetTelegram(v)
	return _c
}

// SetNillableTelegram sets the "telegram" field if the given value is not nil.
func (_c *UserCreate) SetNillableTelegram(v *string) *UserCreate {
	if v != nil {
		_c.SetTelegram(*v)
	}
	return _c
}

// SetSocialAccounts sets the "social_accounts" field.
func (_c *UserCreate) SetSocialAccounts(v map[string]interface{}) *UserCreate {
	_c.mutation.SetSocialAccounts(v)
	return _c
}

// SetPrimaryBadgeID sets the "primary_badge_id" field.
func (_c *UserCreate) SetPrimaryBadgeID(v int) *UserCreate {
	_c.mutation.SetPrimaryBadgeID(v)
	return _c
}

// SetNillablePrimaryBadgeID sets the "primary_badge_id" field if the given value is not nil.
func (_c *UserCreate) SetNillablePrimaryBadgeID(v *int) *UserCreate {
	if v != nil {
		_c.SetPrimaryBadgeID(*v)
	}
	return _c
}

// SetTotpSecret sets the "totp_secret" field.
func (_c *UserCreate) SetTotpSecret(v string) *UserCreate {
	_c.mutation.SetTotpSecret(v)
	return _c
}

// SetNillableTotpSecret sets the "totp_secret" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpSecret(v *string) *UserCreate {
	if v != nil {
		_c.SetTotpSecret(*v)
	}
	return _c
}

// SetTotpEnabled sets the "totp_enabled" field.
func (_c *UserCreate) SetTotpEnabled(v bool) *UserCreate {
	_c.mutation.SetTotpEnabled(v)
	return _c
}

// SetNillableTotpEnabled sets the "totp_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetTotpEnabled(*v)
	}
	return _c
}

// SetTotpVerified sets the "totp_verified" field.
func (_c *UserCreate) SetTotpVerified(v bool) *UserCreate {
	_c.mutation.SetTotpVerified(v)
	return _c
}

// SetNillableTotpVerified sets the "totp_verified" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpVerified(v *bool) *UserCreate {
	if v != nil {
		_c.SetTotpVerified(*v)
	}
	return _c
}

// SetTotpVerifiedAt sets the "totp_verified_at" field.
func (_c *UserCreate) SetTotpVerifiedAt(v time.Time) *UserCreate {
	_c.mutation.SetTotpVerifiedAt(v)
	return _c
}

// SetNillableTotpVerifiedAt sets the "totp_verified_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpVerifiedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetTotpVerifiedAt(*v)
	}
	return _c
}

// SetFailedLoginAttempts sets the "failed_login_attempts" field.
func (_c *UserCreate) SetFailedLoginAttempts(v int) *UserCreate {
	_c.mutation.SetFailedLoginAttempts(v)
	return _c
}

// SetNillableFailedLoginAttempts sets the "failed_login_attempts" field if the given value is not nil.
func (_c *UserCreate) SetNillableFailedLoginAttempts(v *int) *UserCreate {
	if v != nil {
		_c.SetFailedLoginAttempts(*v)
	}
	return _c
}

// SetLastFailedAt sets the "last_failed_at" field.
func (_c *UserCreate) SetLastFailedAt(v time.Time) *UserCreate {
	_c.mutation.SetLastFailedAt(v)
	return _c
}

// SetNillableLastFailedAt sets the "last_failed_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastFailedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastFailedAt(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *UserCreate) SetLastLoginAt(v time.Time) *UserCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLoginAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetLastLoginIP sets the "last_login_ip" field.
func (_c *UserCreate) SetLastLoginIP(v string) *UserCreate {
	_c.mutation.SetLastLoginIP(v)
	return _c
}

// SetNillableLastLoginIP sets the "last_login_ip" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLoginIP(v *string) *UserCreate {
	if v != nil {
		_c.SetLastLoginIP(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *UserCreate) SetLockedUntil(v time.Time) *UserCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *UserCreate) SetNillableLockedUntil(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetLockReason sets the "lock_reason" field.
func (_c *UserCreate) SetLockReason(v string) *UserCreate {
	_c.mutation.SetLockReason(v)
	return _c
}

// SetNillableLockReason sets the "lock_reason" field if the given value is not nil.
func (_c *UserCreate) SetNillableLockReason(v *string) *UserCreate {
	if v != nil {
		_c.SetLockReason(*v)
	}
	return _c
}

// AddPasskeyIDs adds the "passkeys" edge to the Passkey entity by IDs.
func (_c *UserCreate) AddPasskeyIDs(ids ...int) *UserCreate {
	_c.mutation.AddPasskeyIDs(ids...)
	return _c
}

// AddPasskeys adds the "passkeys" edges to the Passkey entity.
func (_c *UserCreate) AddPasskeys(v ...*Passkey) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPasskeyIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_c *UserCreate) AddSessionIDs(ids ...int) *UserCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_c *UserCreate) AddSessions(v ...*Session) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// AddBackupCodeIDs adds the "backup_codes" edge to the BackupCode entity by IDs.
func (_c *UserCreate) AddBackupCodeIDs(ids ...int) *UserCreate {
	_c.mutation.AddBackupCodeIDs(ids...)
	return _c
}

// AddBackupCodes adds the "backup_codes" edges to the BackupCode entity.
func (_c *UserCreate) AddBackupCodes(v ...*BackupCode) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBackupCodeIDs(ids...)
}

// AddThreadIDs adds the "threads" edge to the Thread entity by IDs.
func (_c *UserCreate) AddThreadIDs(ids ...int) *UserCreate {
	_c.mutation.AddThreadIDs(ids...)
	return _c
}

// AddThreads adds the "threads" edges to the Thread entity.
func (_c *UserCreate) AddThreads(v ...*Thread) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddThreadIDs(ids...)
}

// AddUserBadgeIDs adds the "user_badges" edge to the UserBadge entity by IDs.
func (_c *UserCreate) AddUserBadgeIDs(ids ...int) *UserCreate {
	_c.mutation.AddUserBadgeIDs(ids...)
	return _c
}

// AddUserBadges adds the "user_badges" edges to the UserBadge entity.
func (_c *UserCreate) AddUserBadges(v ...*UserBadge) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserBadgeIDs(ids...)
}

// AddSessionLockIDs adds the "session_locks" edge to the SessionLock entity by IDs.
func (_c *UserCreate) AddSessionLockIDs(ids ...int) *UserCreate {
	_c.mutation.AddSessionLockIDs(ids...)
	return _c
}

// AddSessionLocks adds the "session_locks" edges to the SessionLock entity.
func (_c *UserCreate) AddSessionLocks(v ...*SessionLock) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionLockIDs(ids...)
}

// AddEmailVerificationTokenIDs adds the "email_verification_tokens" edge to the EmailVerificationToken entity by IDs.
func (_c *UserCreate) AddEmailVerificationTokenIDs(ids ...int) *UserCreate {
	_c.mutation.AddEmailVerificationTokenIDs(ids...)
	return _c
}

// AddEmailVerificationTokens adds the "email_verification_tokens" edges to the EmailVerificationToken entity.
func (_c *UserCreate) AddEmailVerificationTokens(v ...*EmailVerificationToken) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmailVerificationTokenIDs(ids...)
}

// AddPasswordResetTokenIDs adds the "password_reset_tokens" edge to the PasswordResetToken entity by IDs.
func (_c *UserCreate) AddPasswordResetTokenIDs(ids ...int) *UserCreate {
	_c.mutation.AddPasswordResetTokenIDs(ids...)
	return _c
}

// AddPasswordResetTokens adds the "password_reset_tokens" edges to the PasswordResetToken entity.
func (_c *UserCreate) AddPasswordResetTokens(v ...*PasswordResetToken) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPasswordResetTokenIDs(ids...)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_c *UserCreate) AddCredentialIDs(ids ...int) *UserCreate {
	_c.mutation.AddCredentialIDs(ids...)
	return _c
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_c *UserCreate) AddCredentials(v ...*Credential) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCredentialIDs(ids...)
}

// AddTotpPendingTokenIDs adds the "totp_pending_tokens" edge to the TOTPPendingToken entity by IDs.
func (_c *UserCreate) AddTotpPendingTokenIDs(ids ...int) *UserCreate {
	_c.mutation.AddTotpPendingTokenIDs(ids...)
	return _c
}

// AddTotpPendingTokens adds the "totp_pending_tokens" edges to the TOTPPendingToken entity.
func (_c *UserCreate) AddTotpPendingTokens(v ...*TOTPPendingToken) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTotpPendingTokenIDs(ids...)
}

// AddSecurityEventIDs adds the "security_events" edge to the SecurityEvent entity by IDs.
func (_c *UserCreate) AddSecurityEventIDs(ids ...int) *UserCreate {
	_c.mutation.AddSecurityEventIDs(ids...)
	return _c
}

// AddSecurityEvents adds the "security_events" edges to the SecurityEvent entity.
func (_c *UserCreate) AddSecurityEvents(v ...*SecurityEvent) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSecurityEventIDs(ids...)
}

// AddDeviceFingerprintIDs adds the "device_fingerprints" edge to the DeviceFingerprint entity by IDs.
func (_c *UserCreate) AddDeviceFingerprintIDs(ids ...int) *UserCreate {
	_c.mutation.AddDeviceFingerprintIDs(ids...)
	return _c
}

// AddDeviceFingerprints adds the "device_fingerprints" edges to the DeviceFingerprint entity.
func (_c *UserCreate) AddDeviceFingerprints(v ...*DeviceFingerprint) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeviceFingerprintIDs(ids...)
}

// AddDeviceUserMappingIDs adds the "device_user_mappings" edge to the DeviceUserMapping entity by IDs.
func (_c *UserCreate) AddDeviceUserMappingIDs(ids ...int) *UserCreate {
	_c.mutation.AddDeviceUserMappingIDs(ids...)
	return _c
}

// AddDeviceUserMappings adds the "device_user_mappings" edges to the DeviceUserMapping entity.
func (_c *UserCreate) AddDeviceUserMappings(v ...*DeviceUserMapping) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeviceUserMappingIDs(ids...)
}

// AddSudoSessionIDs adds the "sudo_sessions" edge to the SudoSession entity by IDs.
func (_c *UserCreate) AddSudoSessionIDs(ids ...int) *UserCreate {
	_c.mutation.AddSudoSessionIDs(ids...)
	return _c
}

// AddSudoSessions adds the "sudo_sessions" edges to the SudoSession entity.
func (_c *UserCreate) AddSudoSessions(v ...*SudoSession) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSudoSessionIDs(ids...)
}

// SetPrimaryBadge sets the "primary_badge" edge to the Badge entity.
func (_c *UserCreate) SetPrimaryBadge(v *Badge) *UserCreate {
	return _c.SetPrimaryBadgeID(v.ID)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		v := user.DefaultEmailVerified
		_c.mutation.SetEmailVerified(v)
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		v := user.DefaultAvatarURL
		_c.mutation.SetAvatarURL(v)
	}
	if _, ok := _c.mutation.Bio(); !ok {
		v := user.DefaultBio
		_c.mutation.SetBio(v)
	}
	if _, ok := _c.mutation.Pronouns(); !ok {
		v := user.DefaultPronouns
		_c.mutation.SetPronouns(v)
	}
	if _, ok := _c.mutation.Company(); !ok {
		v := user.DefaultCompany
		_c.mutation.SetCompany(v)
	}
	if _, ok := _c.mutation.Telegram(); !ok {
		v := user.DefaultTelegram
		_c.mutation.SetTelegram(v)
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		v := user.DefaultTotpEnabled
		_c.mutation.SetTotpEnabled(v)
	}
	if _, ok := _c.mutation.TotpVerified(); !ok {
		v := user.DefaultTotpVerified
		_c.mutation.SetTotpVerified(v)
	}
	if _, ok := _c.mutation.FailedLoginAttempts(); !ok {
		v := user.DefaultFailedLoginAttempts
		_c.mutation.SetFailedLoginAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		return &ValidationError{Name: "email_verified", err: errors.New(`ent: missing required field "User.email_verified"`)}
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		return &ValidationError{Name: "totp_enabled", err: errors.New(`ent: missing required field "User.totp_enabled"`)}
	}
	if _, ok := _c.mutation.TotpVerified(); !ok {
		return &ValidationError{Name: "totp_verified", err: errors.New(`ent: missing required field "User.totp_verified"`)}
	}
	if _, ok := _c.mutation.FailedLoginAttempts(); !ok {
		return &ValidationError{Name: "failed_login_attempts", err: errors.New(`ent: missing required field "User.failed_login_attempts"`)}
	}
	if v, ok := _c.mutation.LastLoginIP(); ok {
		if err := user.LastLoginIPValidator(v); err != nil {
			return &ValidationError{Name: "last_login_ip", err: fmt.Errorf(`ent: validator failed for field "User.last_login_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LockReason(); ok {
		if err := user.LockReasonValidator(v); err != nil {
			return &ValidationError{Name: "lock_reason", err: fmt.Errorf(`ent: validator failed for field "User.lock_reason": %w`, err)}
		}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.EmailVerified(); ok {
		_spec.SetField(user.FieldEmailVerified, field.TypeBool, value)
		_node.EmailVerified = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
		_node.FullName = &value
	}
	if value, ok := _c.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
		_node.Bio = value
	}
	if value, ok := _c.mutation.Pronouns(); ok {
		_spec.SetField(user.FieldPronouns, field.TypeString, value)
		_node.Pronouns = value
	}
	if value, ok := _c.mutation.Company(); ok {
		_spec.SetField(user.FieldCompany, field.TypeString, value)
		_node.Company = value
	}
	if value, ok := _c.mutation.Telegram(); ok {
		_spec.SetField(user.FieldTelegram, field.TypeString, value)
		_node.Telegram = value
	}
	if value, ok := _c.mutation.SocialAccounts(); ok {
		_spec.SetField(user.FieldSocialAccounts, field.TypeJSON, value)
		_node.SocialAccounts = value
	}
	if value, ok := _c.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
		_node.TotpSecret = &value
	}
	if value, ok := _c.mutation.TotpEnabled(); ok {
		_spec.SetField(user.FieldTotpEnabled, field.TypeBool, value)
		_node.TotpEnabled = value
	}
	if value, ok := _c.mutation.TotpVerified(); ok {
		_spec.SetField(user.FieldTotpVerified, field.TypeBool, value)
		_node.TotpVerified = value
	}
	if value, ok := _c.mutation.TotpVerifiedAt(); ok {
		_spec.SetField(user.FieldTotpVerifiedAt, field.TypeTime, value)
		_node.TotpVerifiedAt = &value
	}
	if value, ok := _c.mutation.FailedLoginAttempts(); ok {
		_spec.SetField(user.FieldFailedLoginAttempts, field.TypeInt, value)
		_node.FailedLoginAttempts = value
	}
	if value, ok := _c.mutation.LastFailedAt(); ok {
		_spec.SetField(user.FieldLastFailedAt, field.TypeTime, value)
		_node.LastFailedAt = &value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if value, ok := _c.mutation.LastLoginIP(); ok {
		_spec.SetField(user.FieldLastLoginIP, field.TypeString, value)
		_node.LastLoginIP = value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(user.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if value, ok := _c.mutation.LockReason(); ok {
		_spec.SetField(user.FieldLockReason, field.TypeString, value)
		_node.LockReason = value
	}
	if nodes := _c.mutation.PasskeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PasskeysTable,
			Columns: []string{user.PasskeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BackupCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BackupCodesTable,
			Columns: []string{user.BackupCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ThreadsTable,
			Columns: []string{user.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserBadgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserBadgesTable,
			Columns: []string{user.UserBadgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbadge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionLocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionLocksTable,
			Columns: []string{user.SessionLocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionlock.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmailVerificationTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EmailVerificationTokensTable,
			Columns: []string{user.EmailVerificationTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailverificationtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PasswordResetTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PasswordResetTokensTable,
			Columns: []string{user.PasswordResetTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(passwordresettoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CredentialsTable,
			Columns: []string{user.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TotpPendingTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpPendingTokensTable,
			Columns: []string{user.TotpPendingTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totppendingtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SecurityEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SecurityEventsTable,
			Columns: []string{user.SecurityEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(securityevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceFingerprintsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DeviceFingerprintsTable,
			Columns: []string{user.DeviceFingerprintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicefingerprint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceUserMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DeviceUserMappingsTable,
			Columns: []string{user.DeviceUserMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceusermapping.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SudoSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SudoSessionsTable,
			Columns: []string{user.SudoSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sudosession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PrimaryBadgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.PrimaryBadgeTable,
			Columns: []string{user.PrimaryBadgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(badge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrimaryBadgeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
