// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-gin/ent/predicate"
	"backend-gin/ent/user"
	"backend-gin/ent/validationcase"
	"backend-gin/ent/validationcaselog"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ValidationCaseLogQuery is the builder for querying ValidationCaseLog entities.
type ValidationCaseLogQuery struct {
	config
	ctx                *QueryContext
	order              []validationcaselog.OrderOption
	inters             []Interceptor
	predicates         []predicate.ValidationCaseLog
	withValidationCase *ValidationCaseQuery
	withActorUser      *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ValidationCaseLogQuery builder.
func (_q *ValidationCaseLogQuery) Where(ps ...predicate.ValidationCaseLog) *ValidationCaseLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ValidationCaseLogQuery) Limit(limit int) *ValidationCaseLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ValidationCaseLogQuery) Offset(offset int) *ValidationCaseLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ValidationCaseLogQuery) Unique(unique bool) *ValidationCaseLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ValidationCaseLogQuery) Order(o ...validationcaselog.OrderOption) *ValidationCaseLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryValidationCase chains the current query on the "validation_case" edge.
func (_q *ValidationCaseLogQuery) QueryValidationCase() *ValidationCaseQuery {
	query := (&ValidationCaseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validationcaselog.Table, validationcaselog.FieldID, selector),
			sqlgraph.To(validationcase.Table, validationcase.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, validationcaselog.ValidationCaseTable, validationcaselog.ValidationCaseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActorUser chains the current query on the "actor_user" edge.
func (_q *ValidationCaseLogQuery) QueryActorUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validationcaselog.Table, validationcaselog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, validationcaselog.ActorUserTable, validationcaselog.ActorUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ValidationCaseLog entity from the query.
// Returns a *NotFoundError when no ValidationCaseLog was found.
func (_q *ValidationCaseLogQuery) First(ctx context.Context) (*ValidationCaseLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{validationcaselog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) FirstX(ctx context.Context) *ValidationCaseLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ValidationCaseLog ID from the query.
// Returns a *NotFoundError when no ValidationCaseLog ID was found.
func (_q *ValidationCaseLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{validationcaselog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ValidationCaseLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ValidationCaseLog entity is found.
// Returns a *NotFoundError when no ValidationCaseLog entities are found.
func (_q *ValidationCaseLogQuery) Only(ctx context.Context) (*ValidationCaseLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{validationcaselog.Label}
	default:
		return nil, &NotSingularError{validationcaselog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) OnlyX(ctx context.Context) *ValidationCaseLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ValidationCaseLog ID in the query.
// Returns a *NotSingularError when more than one ValidationCaseLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ValidationCaseLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{validationcaselog.Label}
	default:
		err = &NotSingularError{validationcaselog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ValidationCaseLogs.
func (_q *ValidationCaseLogQuery) All(ctx context.Context) ([]*ValidationCaseLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ValidationCaseLog, *ValidationCaseLogQuery]()
	return withInterceptors[[]*ValidationCaseLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) AllX(ctx context.Context) []*ValidationCaseLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ValidationCaseLog IDs.
func (_q *ValidationCaseLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(validationcaselog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ValidationCaseLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ValidationCaseLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ValidationCaseLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ValidationCaseLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ValidationCaseLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ValidationCaseLogQuery) Clone() *ValidationCaseLogQuery {
	if _q == nil {
		return nil
	}
	return &ValidationCaseLogQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]validationcaselog.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ValidationCaseLog{}, _q.predicates...),
		withValidationCase: _q.withValidationCase.Clone(),
		withActorUser:      _q.withActorUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithValidationCase tells the query-builder to eager-load the nodes that are connected to
// the "validation_case" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ValidationCaseLogQuery) WithValidationCase(opts ...func(*ValidationCaseQuery)) *ValidationCaseLogQuery {
	query := (&ValidationCaseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withValidationCase = query
	return _q
}

// WithActorUser tells the query-builder to eager-load the nodes that are connected to
// the "actor_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ValidationCaseLogQuery) WithActorUser(opts ...func(*UserQuery)) *ValidationCaseLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActorUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ValidationCaseLog.Query().
//		GroupBy(validationcaselog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ValidationCaseLogQuery) GroupBy(field string, fields ...string) *ValidationCaseLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ValidationCaseLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = validationcaselog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ValidationCaseLog.Query().
//		Select(validationcaselog.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ValidationCaseLogQuery) Select(fields ...string) *ValidationCaseLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ValidationCaseLogSelect{ValidationCaseLogQuery: _q}
	sbuild.label = validationcaselog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ValidationCaseLogSelect configured with the given aggregations.
func (_q *ValidationCaseLogQuery) Aggregate(fns ...AggregateFunc) *ValidationCaseLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ValidationCaseLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !validationcaselog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ValidationCaseLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ValidationCaseLog, error) {
	var (
		nodes       = []*ValidationCaseLog{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withValidationCase != nil,
			_q.withActorUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ValidationCaseLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ValidationCaseLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withValidationCase; query != nil {
		if err := _q.loadValidationCase(ctx, query, nodes, nil,
			func(n *ValidationCaseLog, e *ValidationCase) { n.Edges.ValidationCase = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withActorUser; query != nil {
		if err := _q.loadActorUser(ctx, query, nodes, nil,
			func(n *ValidationCaseLog, e *User) { n.Edges.ActorUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ValidationCaseLogQuery) loadValidationCase(ctx context.Context, query *ValidationCaseQuery, nodes []*ValidationCaseLog, init func(*ValidationCaseLog), assign func(*ValidationCaseLog, *ValidationCase)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ValidationCaseLog)
	for i := range nodes {
		fk := nodes[i].ValidationCaseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(validationcase.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "validation_case_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ValidationCaseLogQuery) loadActorUser(ctx context.Context, query *UserQuery, nodes []*ValidationCaseLog, init func(*ValidationCaseLog), assign func(*ValidationCaseLog, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ValidationCaseLog)
	for i := range nodes {
		if nodes[i].ActorUserID == nil {
			continue
		}
		fk := *nodes[i].ActorUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "actor_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ValidationCaseLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ValidationCaseLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(validationcaselog.Table, validationcaselog.Columns, sqlgraph.NewFieldSpec(validationcaselog.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, validationcaselog.FieldID)
		for i := range fields {
			if fields[i] != validationcaselog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withValidationCase != nil {
			_spec.Node.AddColumnOnce(validationcaselog.FieldValidationCaseID)
		}
		if _q.withActorUser != nil {
			_spec.Node.AddColumnOnce(validationcaselog.FieldActorUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ValidationCaseLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(validationcaselog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = validationcaselog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ValidationCaseLogGroupBy is the group-by builder for ValidationCaseLog entities.
type ValidationCaseLogGroupBy struct {
	selector
	build *ValidationCaseLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ValidationCaseLogGroupBy) Aggregate(fns ...AggregateFunc) *ValidationCaseLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ValidationCaseLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValidationCaseLogQuery, *ValidationCaseLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ValidationCaseLogGroupBy) sqlScan(ctx context.Context, root *ValidationCaseLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ValidationCaseLogSelect is the builder for selecting fields of ValidationCaseLog entities.
type ValidationCaseLogSelect struct {
	*ValidationCaseLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ValidationCaseLogSelect) Aggregate(fns ...AggregateFunc) *ValidationCaseLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ValidationCaseLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValidationCaseLogQuery, *ValidationCaseLogSelect](ctx, _s.ValidationCaseLogQuery, _s, _s.inters, v)
}

func (_s *ValidationCaseLogSelect) sqlScan(ctx context.Context, root *ValidationCaseLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
