// Code generated by ent, DO NOT EDIT.

package endorsement

import (
	"backend-gin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldDeletedAt, v))
}

// ValidationCaseID applies equality check predicate on the "validation_case_id" field. It's identical to ValidationCaseIDEQ.
func ValidationCaseID(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldValidationCaseID, v))
}

// ValidatorUserID applies equality check predicate on the "validator_user_id" field. It's identical to ValidatorUserIDEQ.
func ValidatorUserID(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldValidatorUserID, v))
}

// CertifiedArtifactDocumentID applies equality check predicate on the "certified_artifact_document_id" field. It's identical to CertifiedArtifactDocumentIDEQ.
func CertifiedArtifactDocumentID(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldCertifiedArtifactDocumentID, v))
}

// Stance applies equality check predicate on the "stance" field. It's identical to StanceEQ.
func Stance(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldStance, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotNull(FieldDeletedAt))
}

// ValidationCaseIDEQ applies the EQ predicate on the "validation_case_id" field.
func ValidationCaseIDEQ(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDNEQ applies the NEQ predicate on the "validation_case_id" field.
func ValidationCaseIDNEQ(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDIn applies the In predicate on the "validation_case_id" field.
func ValidationCaseIDIn(vs ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldValidationCaseID, vs...))
}

// ValidationCaseIDNotIn applies the NotIn predicate on the "validation_case_id" field.
func ValidationCaseIDNotIn(vs ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldValidationCaseID, vs...))
}

// ValidatorUserIDEQ applies the EQ predicate on the "validator_user_id" field.
func ValidatorUserIDEQ(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldValidatorUserID, v))
}

// ValidatorUserIDNEQ applies the NEQ predicate on the "validator_user_id" field.
func ValidatorUserIDNEQ(v int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldValidatorUserID, v))
}

// ValidatorUserIDIn applies the In predicate on the "validator_user_id" field.
func ValidatorUserIDIn(vs ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldValidatorUserID, vs...))
}

// ValidatorUserIDNotIn applies the NotIn predicate on the "validator_user_id" field.
func ValidatorUserIDNotIn(vs ...int) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldValidatorUserID, vs...))
}

// CertifiedArtifactDocumentIDEQ applies the EQ predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDNEQ applies the NEQ predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDNEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDIn applies the In predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldCertifiedArtifactDocumentID, vs...))
}

// CertifiedArtifactDocumentIDNotIn applies the NotIn predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDNotIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldCertifiedArtifactDocumentID, vs...))
}

// CertifiedArtifactDocumentIDGT applies the GT predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDGT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDGTE applies the GTE predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDGTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDLT applies the LT predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDLT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDLTE applies the LTE predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDLTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDContains applies the Contains predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDContains(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContains(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDHasPrefix applies the HasPrefix predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDHasPrefix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasPrefix(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDHasSuffix applies the HasSuffix predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDHasSuffix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasSuffix(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDIsNil applies the IsNil predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDIsNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIsNull(FieldCertifiedArtifactDocumentID))
}

// CertifiedArtifactDocumentIDNotNil applies the NotNil predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDNotNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotNull(FieldCertifiedArtifactDocumentID))
}

// CertifiedArtifactDocumentIDEqualFold applies the EqualFold predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDEqualFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEqualFold(FieldCertifiedArtifactDocumentID, v))
}

// CertifiedArtifactDocumentIDContainsFold applies the ContainsFold predicate on the "certified_artifact_document_id" field.
func CertifiedArtifactDocumentIDContainsFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContainsFold(FieldCertifiedArtifactDocumentID, v))
}

// StanceEQ applies the EQ predicate on the "stance" field.
func StanceEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldStance, v))
}

// StanceNEQ applies the NEQ predicate on the "stance" field.
func StanceNEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldStance, v))
}

// StanceIn applies the In predicate on the "stance" field.
func StanceIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldStance, vs...))
}

// StanceNotIn applies the NotIn predicate on the "stance" field.
func StanceNotIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldStance, vs...))
}

// StanceGT applies the GT predicate on the "stance" field.
func StanceGT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldStance, v))
}

// StanceGTE applies the GTE predicate on the "stance" field.
func StanceGTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldStance, v))
}

// StanceLT applies the LT predicate on the "stance" field.
func StanceLT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldStance, v))
}

// StanceLTE applies the LTE predicate on the "stance" field.
func StanceLTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldStance, v))
}

// StanceContains applies the Contains predicate on the "stance" field.
func StanceContains(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContains(FieldStance, v))
}

// StanceHasPrefix applies the HasPrefix predicate on the "stance" field.
func StanceHasPrefix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasPrefix(FieldStance, v))
}

// StanceHasSuffix applies the HasSuffix predicate on the "stance" field.
func StanceHasSuffix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasSuffix(FieldStance, v))
}

// StanceIsNil applies the IsNil predicate on the "stance" field.
func StanceIsNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIsNull(FieldStance))
}

// StanceNotNil applies the NotNil predicate on the "stance" field.
func StanceNotNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotNull(FieldStance))
}

// StanceEqualFold applies the EqualFold predicate on the "stance" field.
func StanceEqualFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEqualFold(FieldStance, v))
}

// StanceContainsFold applies the ContainsFold predicate on the "stance" field.
func StanceContainsFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContainsFold(FieldStance, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Endorsement {
	return predicate.Endorsement(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Endorsement {
	return predicate.Endorsement(sql.FieldContainsFold(FieldNote, v))
}

// HasValidationCase applies the HasEdge predicate on the "validation_case" edge.
func HasValidationCase() predicate.Endorsement {
	return predicate.Endorsement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ValidationCaseTable, ValidationCaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasValidationCaseWith applies the HasEdge predicate on the "validation_case" edge with a given conditions (other predicates).
func HasValidationCaseWith(preds ...predicate.ValidationCase) predicate.Endorsement {
	return predicate.Endorsement(func(s *sql.Selector) {
		step := newValidationCaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasValidatorUser applies the HasEdge predicate on the "validator_user" edge.
func HasValidatorUser() predicate.Endorsement {
	return predicate.Endorsement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ValidatorUserTable, ValidatorUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasValidatorUserWith applies the HasEdge predicate on the "validator_user" edge with a given conditions (other predicates).
func HasValidatorUserWith(preds ...predicate.User) predicate.Endorsement {
	return predicate.Endorsement(func(s *sql.Selector) {
		step := newValidatorUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Endorsement) predicate.Endorsement {
	return predicate.Endorsement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Endorsement) predicate.Endorsement {
	return predicate.Endorsement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Endorsement) predicate.Endorsement {
	return predicate.Endorsement(sql.NotPredicates(p))
}
