// Code generated by ent, DO NOT EDIT.

package badge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the badge type in the database.
	Label = "badge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// EdgeUserBadges holds the string denoting the user_badges edge name in mutations.
	EdgeUserBadges = "user_badges"
	// EdgePrimaryUsers holds the string denoting the primary_users edge name in mutations.
	EdgePrimaryUsers = "primary_users"
	// Table holds the table name of the badge in the database.
	Table = "badges"
	// UserBadgesTable is the table that holds the user_badges relation/edge.
	UserBadgesTable = "user_badges"
	// UserBadgesInverseTable is the table name for the UserBadge entity.
	// It exists in this package in order to avoid circular dependency with the "userbadge" package.
	UserBadgesInverseTable = "user_badges"
	// UserBadgesColumn is the table column denoting the user_badges relation/edge.
	UserBadgesColumn = "badge_id"
	// PrimaryUsersTable is the table that holds the primary_users relation/edge.
	PrimaryUsersTable = "users"
	// PrimaryUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PrimaryUsersInverseTable = "users"
	// PrimaryUsersColumn is the table column denoting the primary_users relation/edge.
	PrimaryUsersColumn = "primary_badge_id"
)

// Columns holds all SQL columns for badge fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSlug,
	FieldDescription,
	FieldIconURL,
	FieldColor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// IconURLValidator is a validator for the "icon_url" field. It is called by the builders before save.
	IconURLValidator func(string) error
	// DefaultColor holds the default value on creation for the "color" field.
	DefaultColor string
)

// OrderOption defines the ordering options for the Badge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByUserBadgesCount orders the results by user_badges count.
func ByUserBadgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserBadgesStep(), opts...)
	}
}

// ByUserBadges orders the results by user_badges terms.
func ByUserBadges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserBadgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrimaryUsersCount orders the results by primary_users count.
func ByPrimaryUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrimaryUsersStep(), opts...)
	}
}

// ByPrimaryUsers orders the results by primary_users terms.
func ByPrimaryUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrimaryUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserBadgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserBadgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserBadgesTable, UserBadgesColumn),
	)
}
func newPrimaryUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrimaryUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PrimaryUsersTable, PrimaryUsersColumn),
	)
}
