// Code generated by ent, DO NOT EDIT.

package finaloffer

import (
	"backend-gin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldDeletedAt, v))
}

// ValidationCaseID applies equality check predicate on the "validation_case_id" field. It's identical to ValidationCaseIDEQ.
func ValidationCaseID(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldValidationCaseID, v))
}

// ValidatorUserID applies equality check predicate on the "validator_user_id" field. It's identical to ValidatorUserIDEQ.
func ValidatorUserID(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldValidatorUserID, v))
}

// SubmissionKey applies equality check predicate on the "submission_key" field. It's identical to SubmissionKeyEQ.
func SubmissionKey(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldSubmissionKey, v))
}

// WorkflowCycle applies equality check predicate on the "workflow_cycle" field. It's identical to WorkflowCycleEQ.
func WorkflowCycle(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldWorkflowCycle, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldAmount, v))
}

// HoldHours applies equality check predicate on the "hold_hours" field. It's identical to HoldHoursEQ.
func HoldHours(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldHoldHours, v))
}

// Terms applies equality check predicate on the "terms" field. It's identical to TermsEQ.
func Terms(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldTerms, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldStatus, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldAcceptedAt, v))
}

// RejectedAt applies equality check predicate on the "rejected_at" field. It's identical to RejectedAtEQ.
func RejectedAt(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldRejectedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotNull(FieldDeletedAt))
}

// ValidationCaseIDEQ applies the EQ predicate on the "validation_case_id" field.
func ValidationCaseIDEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDNEQ applies the NEQ predicate on the "validation_case_id" field.
func ValidationCaseIDNEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldValidationCaseID, v))
}

// ValidationCaseIDIn applies the In predicate on the "validation_case_id" field.
func ValidationCaseIDIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldValidationCaseID, vs...))
}

// ValidationCaseIDNotIn applies the NotIn predicate on the "validation_case_id" field.
func ValidationCaseIDNotIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldValidationCaseID, vs...))
}

// ValidatorUserIDEQ applies the EQ predicate on the "validator_user_id" field.
func ValidatorUserIDEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldValidatorUserID, v))
}

// ValidatorUserIDNEQ applies the NEQ predicate on the "validator_user_id" field.
func ValidatorUserIDNEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldValidatorUserID, v))
}

// ValidatorUserIDIn applies the In predicate on the "validator_user_id" field.
func ValidatorUserIDIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldValidatorUserID, vs...))
}

// ValidatorUserIDNotIn applies the NotIn predicate on the "validator_user_id" field.
func ValidatorUserIDNotIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldValidatorUserID, vs...))
}

// SubmissionKeyEQ applies the EQ predicate on the "submission_key" field.
func SubmissionKeyEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldSubmissionKey, v))
}

// SubmissionKeyNEQ applies the NEQ predicate on the "submission_key" field.
func SubmissionKeyNEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldSubmissionKey, v))
}

// SubmissionKeyIn applies the In predicate on the "submission_key" field.
func SubmissionKeyIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldSubmissionKey, vs...))
}

// SubmissionKeyNotIn applies the NotIn predicate on the "submission_key" field.
func SubmissionKeyNotIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldSubmissionKey, vs...))
}

// SubmissionKeyGT applies the GT predicate on the "submission_key" field.
func SubmissionKeyGT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldSubmissionKey, v))
}

// SubmissionKeyGTE applies the GTE predicate on the "submission_key" field.
func SubmissionKeyGTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldSubmissionKey, v))
}

// SubmissionKeyLT applies the LT predicate on the "submission_key" field.
func SubmissionKeyLT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldSubmissionKey, v))
}

// SubmissionKeyLTE applies the LTE predicate on the "submission_key" field.
func SubmissionKeyLTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldSubmissionKey, v))
}

// SubmissionKeyContains applies the Contains predicate on the "submission_key" field.
func SubmissionKeyContains(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContains(FieldSubmissionKey, v))
}

// SubmissionKeyHasPrefix applies the HasPrefix predicate on the "submission_key" field.
func SubmissionKeyHasPrefix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasPrefix(FieldSubmissionKey, v))
}

// SubmissionKeyHasSuffix applies the HasSuffix predicate on the "submission_key" field.
func SubmissionKeyHasSuffix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasSuffix(FieldSubmissionKey, v))
}

// SubmissionKeyIsNil applies the IsNil predicate on the "submission_key" field.
func SubmissionKeyIsNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIsNull(FieldSubmissionKey))
}

// SubmissionKeyNotNil applies the NotNil predicate on the "submission_key" field.
func SubmissionKeyNotNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotNull(FieldSubmissionKey))
}

// SubmissionKeyEqualFold applies the EqualFold predicate on the "submission_key" field.
func SubmissionKeyEqualFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEqualFold(FieldSubmissionKey, v))
}

// SubmissionKeyContainsFold applies the ContainsFold predicate on the "submission_key" field.
func SubmissionKeyContainsFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContainsFold(FieldSubmissionKey, v))
}

// WorkflowCycleEQ applies the EQ predicate on the "workflow_cycle" field.
func WorkflowCycleEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldWorkflowCycle, v))
}

// WorkflowCycleNEQ applies the NEQ predicate on the "workflow_cycle" field.
func WorkflowCycleNEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldWorkflowCycle, v))
}

// WorkflowCycleIn applies the In predicate on the "workflow_cycle" field.
func WorkflowCycleIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldWorkflowCycle, vs...))
}

// WorkflowCycleNotIn applies the NotIn predicate on the "workflow_cycle" field.
func WorkflowCycleNotIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldWorkflowCycle, vs...))
}

// WorkflowCycleGT applies the GT predicate on the "workflow_cycle" field.
func WorkflowCycleGT(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldWorkflowCycle, v))
}

// WorkflowCycleGTE applies the GTE predicate on the "workflow_cycle" field.
func WorkflowCycleGTE(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldWorkflowCycle, v))
}

// WorkflowCycleLT applies the LT predicate on the "workflow_cycle" field.
func WorkflowCycleLT(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldWorkflowCycle, v))
}

// WorkflowCycleLTE applies the LTE predicate on the "workflow_cycle" field.
func WorkflowCycleLTE(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldWorkflowCycle, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldAmount, v))
}

// HoldHoursEQ applies the EQ predicate on the "hold_hours" field.
func HoldHoursEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldHoldHours, v))
}

// HoldHoursNEQ applies the NEQ predicate on the "hold_hours" field.
func HoldHoursNEQ(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldHoldHours, v))
}

// HoldHoursIn applies the In predicate on the "hold_hours" field.
func HoldHoursIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldHoldHours, vs...))
}

// HoldHoursNotIn applies the NotIn predicate on the "hold_hours" field.
func HoldHoursNotIn(vs ...int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldHoldHours, vs...))
}

// HoldHoursGT applies the GT predicate on the "hold_hours" field.
func HoldHoursGT(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldHoldHours, v))
}

// HoldHoursGTE applies the GTE predicate on the "hold_hours" field.
func HoldHoursGTE(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldHoldHours, v))
}

// HoldHoursLT applies the LT predicate on the "hold_hours" field.
func HoldHoursLT(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldHoldHours, v))
}

// HoldHoursLTE applies the LTE predicate on the "hold_hours" field.
func HoldHoursLTE(v int) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldHoldHours, v))
}

// TermsEQ applies the EQ predicate on the "terms" field.
func TermsEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldTerms, v))
}

// TermsNEQ applies the NEQ predicate on the "terms" field.
func TermsNEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldTerms, v))
}

// TermsIn applies the In predicate on the "terms" field.
func TermsIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldTerms, vs...))
}

// TermsNotIn applies the NotIn predicate on the "terms" field.
func TermsNotIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldTerms, vs...))
}

// TermsGT applies the GT predicate on the "terms" field.
func TermsGT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldTerms, v))
}

// TermsGTE applies the GTE predicate on the "terms" field.
func TermsGTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldTerms, v))
}

// TermsLT applies the LT predicate on the "terms" field.
func TermsLT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldTerms, v))
}

// TermsLTE applies the LTE predicate on the "terms" field.
func TermsLTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldTerms, v))
}

// TermsContains applies the Contains predicate on the "terms" field.
func TermsContains(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContains(FieldTerms, v))
}

// TermsHasPrefix applies the HasPrefix predicate on the "terms" field.
func TermsHasPrefix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasPrefix(FieldTerms, v))
}

// TermsHasSuffix applies the HasSuffix predicate on the "terms" field.
func TermsHasSuffix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasSuffix(FieldTerms, v))
}

// TermsIsNil applies the IsNil predicate on the "terms" field.
func TermsIsNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIsNull(FieldTerms))
}

// TermsNotNil applies the NotNil predicate on the "terms" field.
func TermsNotNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotNull(FieldTerms))
}

// TermsEqualFold applies the EqualFold predicate on the "terms" field.
func TermsEqualFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEqualFold(FieldTerms, v))
}

// TermsContainsFold applies the ContainsFold predicate on the "terms" field.
func TermsContainsFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContainsFold(FieldTerms, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldContainsFold(FieldStatus, v))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldAcceptedAt, v))
}

// AcceptedAtIsNil applies the IsNil predicate on the "accepted_at" field.
func AcceptedAtIsNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIsNull(FieldAcceptedAt))
}

// AcceptedAtNotNil applies the NotNil predicate on the "accepted_at" field.
func AcceptedAtNotNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotNull(FieldAcceptedAt))
}

// RejectedAtEQ applies the EQ predicate on the "rejected_at" field.
func RejectedAtEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldEQ(FieldRejectedAt, v))
}

// RejectedAtNEQ applies the NEQ predicate on the "rejected_at" field.
func RejectedAtNEQ(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNEQ(FieldRejectedAt, v))
}

// RejectedAtIn applies the In predicate on the "rejected_at" field.
func RejectedAtIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIn(FieldRejectedAt, vs...))
}

// RejectedAtNotIn applies the NotIn predicate on the "rejected_at" field.
func RejectedAtNotIn(vs ...time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotIn(FieldRejectedAt, vs...))
}

// RejectedAtGT applies the GT predicate on the "rejected_at" field.
func RejectedAtGT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGT(FieldRejectedAt, v))
}

// RejectedAtGTE applies the GTE predicate on the "rejected_at" field.
func RejectedAtGTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldGTE(FieldRejectedAt, v))
}

// RejectedAtLT applies the LT predicate on the "rejected_at" field.
func RejectedAtLT(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLT(FieldRejectedAt, v))
}

// RejectedAtLTE applies the LTE predicate on the "rejected_at" field.
func RejectedAtLTE(v time.Time) predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldLTE(FieldRejectedAt, v))
}

// RejectedAtIsNil applies the IsNil predicate on the "rejected_at" field.
func RejectedAtIsNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldIsNull(FieldRejectedAt))
}

// RejectedAtNotNil applies the NotNil predicate on the "rejected_at" field.
func RejectedAtNotNil() predicate.FinalOffer {
	return predicate.FinalOffer(sql.FieldNotNull(FieldRejectedAt))
}

// HasValidationCase applies the HasEdge predicate on the "validation_case" edge.
func HasValidationCase() predicate.FinalOffer {
	return predicate.FinalOffer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ValidationCaseTable, ValidationCaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasValidationCaseWith applies the HasEdge predicate on the "validation_case" edge with a given conditions (other predicates).
func HasValidationCaseWith(preds ...predicate.ValidationCase) predicate.FinalOffer {
	return predicate.FinalOffer(func(s *sql.Selector) {
		step := newValidationCaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasValidatorUser applies the HasEdge predicate on the "validator_user" edge.
func HasValidatorUser() predicate.FinalOffer {
	return predicate.FinalOffer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ValidatorUserTable, ValidatorUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasValidatorUserWith applies the HasEdge predicate on the "validator_user" edge with a given conditions (other predicates).
func HasValidatorUserWith(preds ...predicate.User) predicate.FinalOffer {
	return predicate.FinalOffer(func(s *sql.Selector) {
		step := newValidatorUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FinalOffer) predicate.FinalOffer {
	return predicate.FinalOffer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FinalOffer) predicate.FinalOffer {
	return predicate.FinalOffer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FinalOffer) predicate.FinalOffer {
	return predicate.FinalOffer(sql.NotPredicates(p))
}
